### ISSUE TITLE
Can build project correctly

### ISSUE THREAD

**Issue by LDWX** [nuxt/create-nuxt-app#109]

**Comment by LDWX** [comment]
`PS C:\Users\shenxin\Documents\shenxinself\selfProject> npx create-nuxt-app nuxt-render-demo
npx: installed 401 in 19.948s
> Generating Nuxt.js project in C:\Users\shenxin\Documents\shenxinself\selfProject\nuxt-render-demo
? Project name nuxt-render-demo
? Project description My dazzling Nuxt.js project
? Use a custom server framework express
? Use a custom UI framework element-ui
? Choose rendering mode Single Page App
? Use axios module yes
? Use eslint no
? Use prettier yes
? Author name xin.shen
? Choose a package manager npm
Initialized empty Git repository in C:/Users/shenxin/Documents/shenxinself/selfProject/nuxt-render-demo/.git/
npm ERR! Unexpected end of JSON input while parsing near '...d":"^4.0.0","nyc":"^1'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shenxin\AppData\Roaming\npm-cache\_logs\2018-10-08T09_11_47_042Z-debug.log

  To get started:

    cd nuxt-render-demo
    npm run dev

  To build & start for production:

    cd nuxt-render-demo
    npm run build
    npm start`

**Comment by aldarund** [comment]
Something wrong with you npm cache/installation. Clean cache/reinstall or choose yarn as a last step.

**Comment by LDWX** [comment]
@aldarund thank you, i will try it
