### ISSUE TITLE
i deploy the nuxtjs app, but in firefox it show network error，other broswer work well.

### ISSUE THREAD

**Issue by bookyo** [nuxt/create-nuxt-app#131]
i deploy the nuxtjs app, but in firefox it show network error，other broswer work well.
my url : https://cms.moejj.com
you can paste it in firefox and click link, it will show error!

firefox show cors error, but i setting Access-Control-Allow-Origin right,  other  broswer work well only firefox error.

**Comment by aldarund** [comment]
it has nothing to do with nuxt create app. Your server return 404
https://i.imgur.com/3dK6JOm.png
