### ISSUE TITLE
forcing port 3000

### ISSUE THREAD

**Issue by tigernassau** [nuxt/create-nuxt-app#145]

**Comment by aldarund** [comment]
@tigernassau what version of nuxt? there was a bug about it in some early version of 2.x like 2.0 or 2.1

**Comment by matamune94** [comment]
me too  using nuxt latest update, how can change port

**Comment by manniL** [comment]
There are several ways: https://nuxtjs.org/faq/host-port/

**Comment by manniL** [comment]
@matamune94 If you use express or another framework *before* nuxt, you have to set up the port on your own

**Comment by matamune94** [comment]
> @matamune94 can give me Ex ?
