### ISSUE TITLE
Remove unneeded deps

### ISSUE THREAD

**Issue by manniL** [nuxt/create-nuxt-app#147]
### What problem does this feature solve?

`cross-env` (deps)  and `nodemon` (devDeps) are not needed for every project. We should properly guard them as well.

**Comment by MrJmpl3** [comment]
Nodemon and cross-env is needed when i used express or another server js (expressjs , adonis , etc)

**Comment by manniL** [comment]
@MrJmpl3 That's what I was saying :relaxed: 

If you use a Nuxt.js inside a server like express, koa, ... then you need it ofc.

**Comment by clarkdo** [comment]
Fixed in 2.9.1
