### ISSUE TITLE
为何直接初始化项目 跑不起来 npx create-nuxt-app 命令也不行

### ISSUE THREAD

**Issue by BeatsX** [nuxt/create-nuxt-app#165]
<img width="1679" alt="wx20190126-142628 2x" src="https://user-images.githubusercontent.com/26688426/51783544-712ad200-2176-11e9-8adc-e30a44bd6eca.png">
<img width="1678" alt="wx20190126-142611 2x" src="https://user-images.githubusercontent.com/26688426/51783545-77b94980-2176-11e9-8f89-e94bf2fbd0f2.png">

**Comment by ly102412** [comment]
您好这个问题解决了吗

**Comment by BeatsX** [comment]
还没有啊 老哥 以前试过可以  准备熟悉一下 年后做PC端用呢  结果就这样了

**Comment by luxuryLu** [comment]
应该是element-ui升级了，我修改了package.json，把element-ui版本改成2.4.6，重新安装了npm包就可以跑了

**Comment by kevinmarrec** [comment]
Fixed with #167 + #168
