### ISSUE TITLE
npx create-nuxt-app Unexpected token export

### ISSUE THREAD

**Issue by ly102412** [nuxt/create-nuxt-app#166]
Use the ‘ npx create-nuxt-app ’ command to install ‘nuxt’. The runtime prompts ‘Unexpected token export’. Just put the referenced ‘element-ui’ comment to run. 
How can I solve it?
![5c4c4fde00011e2412881248](https://user-images.githubusercontent.com/30214380/51789045-db1b9980-21bf-11e9-80ca-2d6d4fabe8fe.jpg)

**Comment by m4tty-d** [comment]
I have the same problem. :(

**Comment by pokerII** [comment]
I have the same problem. :(

**Comment by BachCN** [comment]
I have the same problem. :(

**Comment by MicroUncle** [comment]
+1 :(

**Comment by luxuryLu** [comment]
I met the same situation, and i opened the 'package.json', modified the version of 'element-ui' to '2.4.6'  ，removed the node_moudules, re-installed the npm packages and it worked~

**Comment by kevinmarrec** [comment]
`element-ui` needs to be transpiled by Nuxt since last versions of the UI library.
Fixed in #167
