### ISSUE TITLE
[Windows] Arrow keyes jump two options in command line menu navigation

### ISSUE THREAD

**Issue by ELFoglalt** [nuxt/create-nuxt-app#170]
## Version
v2.1.1

## Bug in action
![2019-01-29_12-32-07](https://user-images.githubusercontent.com/14253369/51907034-02dc4e80-23c6-11e9-8419-eef2f47eb250.gif)

## Reproduction
Using Git Bash with MinTTY on Windows:

- Create new project using `winpty npx.cmd create-nuxt-app`
- Observe as the up and down arrow keys jump 2 options instead of one in the selection menus

Happened with a fresh install of
 git (2.20.1 x64) + mintty, npm@6.5.0 and npx@10.2.0.

(Replicate of [cmty issue #c101](https://cmty.app/nuxt/create-nuxt-app/issues/c101), since apparently cmty does not work for nuxt/create-nuxt-app)

**Comment by thetre97** [comment]
I also get this with Powershell on Windows 10, but it is fine with Bash/Zsh on Linux.

**Comment by clarkdo** [comment]
@ELFoglalt Could try it now with latest create-nuxt-app ?

**Comment by thetre97** [comment]
I still get this on PowerShell with v2.4.0...

**Comment by clarkdo** [comment]
@thetre97 I tried in my local with PowerShell/Git Bash under Win10, it works fine, could you confirm if you're using create-nuxt-app with latest saojs ?

**Comment by thetre97** [comment]
v2.4.0 shows that i have `"sao": "^1.6.1"` installed...

I've tried using Powershell, Powershell 6, and on Git Bash the arrow keys don't seem to work at all...

PS: https://www.useloom.com/share/aa6b1b2448144cf08abab7ed4488e9f9
Git Bash: https://www.useloom.com/share/d9c473d94b554c99b79b6a7b6176e8df

Windows 10 Insider: 1903
Node 11.8.0

**Comment by ELFoglalt** [comment]
Still happening with `"create-nuxt-app": "^2.4.0"` and `"sao": "^1.6.1"`, with same os/setup as in op.

**Comment by clarkdo** [comment]
@thetre97 @ELFoglalt This issue seemed related to https://github.com/SBoudrias/Inquirer.js/issues/778, could you try the node version mentioned in that issue ?

**Comment by thetre97** [comment]
Just install node v11.10.0, and it works perfectly 👍

**Comment by manniL** [comment]
I pinned the issue and will close it as a workaround is present ☺️
