### ISSUE TITLE
[vuetify ui] Default link color doesn't contrast with background

### ISSUE THREAD

**Issue by rchl** [nuxt/create-nuxt-app#171]
### Version

[v2.1.1](https://github.com/create-nuxt-app/releases/tag/v2.1.1)

### Reproduction link

[https://codesandbox.io/s/319w02xwrp](https://codesandbox.io/s/319w02xwrp)

### Steps to reproduce

1. `npx create-nuxt-app sample-project`
2. Select vuetify as UI framework
3. Run `npm run dev` and open http://localhost:3000 in the browser

### What is expected ?

That the default colors play well together

### What is actually happening?

Links have dark color that almost blends with the background color. Basically deafult colors are poor contrast-wise.

### Additional comments?

![vuetify-colors.png](https://cmty.s3.eu-west-1.amazonaws.com/99351826/66c2ed80-23be-11e9-b478-49939ef6e5f4.png)

**Comment by Codefa** [comment]
@rchl  just go to plugins/vuetify.js and give primary color to blue or whatever you want `primary: colors.blue,`

**Comment by manniL** [comment]
@rchl feel free to send in a PR ☺️

**Comment by Codefa** [comment]
Fixed in latest release 😀
