### ISSUE TITLE
(minor) README always shows yarn build commands

### ISSUE THREAD

**Issue by rick-stevens** [nuxt/create-nuxt-app#179]
Hi! My compiled `README.md` always contains `yarn` build commands, even though I choose `npm` as my package manager during installation (Node v10.15.0, `npx create-nuxt-app`).

**Comment by clarkdo** [comment]
@rick-stevens Could you try latest create-nuxt-app ?

**Comment by rick-stevens** [comment]
@clarkdo It seems to have solved the issue, thanks! 👍
