### ISSUE TITLE
ubuntu 16.04 npx create-nuxt-app

### ISSUE THREAD

**Issue by francoisp** [nuxt/create-nuxt-app#184]
npm -v 6.4.1
 node -v v10.15.1

npx create-nuxt-app

npx: installed 379 in 15.435s

> Generating Nuxt.js project in /home/nuxt
> ? Project name nuxt
> ? Project description My terrific Nuxt.js project
> ? Use a custom server framework none
> ? Choose features to install (Press  to select,  to toggle all,  to invert selection)
> ? Use a custom UI framework none
> ? Use a custom test framework none
> ? Choose rendering mode Universal
> ? Author name
> ? Choose a package manager npm
> ⠙ Installing packages with npm
> ⠸ Installing packages with npm
> ⠴ Installing packages with npm
> ⠧ Installing packages with npm
> ⠦ Installing packages with npm
> ⠇ Installing packages with npm
> ⠋ Installing packages with npm
> /home/nuxt/.npm/_npx/1063227/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
> throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
> ^

Error: Failed to install packages in /home/nuxt
at ChildProcess.ps.on.code (/home/nuxt/.npm/_npx/1063227/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
at ChildProcess.emit (events.js:189:13)
at maybeClose (internal/child_process.js:970:16)
at Socket.stream.socket.on (internal/child_process.js:389:11)
at Socket.emit (events.js:189:13)
at Pipe._handle.close (net.js:600:12)

**Comment by francoisp** [comment]
npx create-nuxt-app      
npx: installed 379 in 15.435s
> Generating Nuxt.js project in /home/nuxt
? Project name nuxt
? Project description My terrific Nuxt.js project
? Use a custom server framework none
? Choose features to install (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Use a custom UI framework none
? Use a custom test framework none
? Choose rendering mode Universal
? Author name 
? Choose a package manager npm
⠙ Installing packages with npm
⠸ Installing packages with npm
⠴ Installing packages with npm
⠧ Installing packages with npm
⠦ Installing packages with npm
⠇ Installing packages with npm
⠋ Installing packages with npm
/home/nuxt/.npm/_npx/1063227/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

Error: Failed to install packages in /home/nuxt
    at ChildProcess.ps.on.code (/home/nuxt/.npm/_npx/1063227/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)

**Comment by francoisp** [comment]
was caused not enough allocated ram to the container, npx create-nuxt-app might use up to 2.5GB

**Comment by RomaricDel** [comment]
I came across the same issue locally, for me the following saved the day

`NODE_OPTIONS=--max_old_space_size=4096 npx create-nuxt-app my-app`

Node version: 10.15.3
NPM: 6.4.1

**Comment by munkhbaatar999** [comment]
Did not work either. Ubuntu 19.04 throwing  SAOError. Any solution in 2019 August?. 
NODE_OPTIONS=--max_old_space_size=4096 npx create-nuxt-app my-app is it work?

**Comment by ScrippsFEE** [comment]
If you are using a version of node less than v8.12.0, then try installing 8.12.0 and rerun create-nuxt-app. I was using 8.11.1. When create-nuxt-app failed, I tried using the Vue CLI to create a new Vue project. I got this error message: 

```bash
error execa@2.0.4: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.11.1"
```

I installed 8.12.0 (using NVM on MacOS) and reran create-nuxt-app and it worked.

**Comment by trandaison** [comment]
This bug is still happen.

- Node v11.8.0
- Yarn 1.17.3
- npm 6.5.0
- Ubuntu 14.04

**Comment by bgalvao** [comment]
Happening to me as well.

- node 10.16.1
- npm 6.9.0
- yarn 1.17.3

Attempted to create nuxt app with both yarn and npx (while picking npm package manager).

**Comment by mfish0005** [comment]
I'm getting the same error.  But it appears no one from core is looking at this issue so maybe someone should open a new one?
`npx create-nuxt-app example-app`
throws this error:
`.../.npm/_npx/335/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)`

**Comment by ScrippsFEE** [comment]
@mfish0005 what version of node are you running? If it's less than 8.12.0, then you need to update your version. This worked for me as described above here: https://github.com/nuxt/create-nuxt-app/issues/184#issuecomment-528179625

**Comment by codergirll** [comment]
> I'm getting the same error. But it appears no one from the nuxt team is looking at this issue so maybe someone should open a new one?
> 
> `npx create-nuxt-app example-app`
> 
> throws this error:
> 
> `.../.npm/_npx/335/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108 throw new SAOError(`Failed to install ${packageName} in ${cwd}`)`

Try this, It may take some time but worked for me.

`sudo chown -R 1000:1000 "/home/you/.npm"`

**Comment by maxshuty** [comment]
I was on node `v8.12.0` and `npm 6.11.1`. I upgraded to node `v12.13.0` and npm `6.13.0` and the issues went away for me. I'm not sure if Yarn has anything to do with this but I decided to not use Yarn and it seemed to work.

**Comment by Xandmore** [comment]
I had the same problem. It disappeared after installing:
node: 12.16.1
npm: 6.13.7

**Comment by EunChan0817** [comment]
I had the same problem.
node : 13.7.0
npm : 6.13.6

**Comment by overbid** [comment]
`sudo apt-get install g++ build-essential`
Before create project is work for me.

**Comment by FallenNoir** [comment]
It seems like yet another problem solved by dancing around changing the node version. In my case it wouldn't install on node 10.5.0 (was installed by default in Laragon) and went pretty smooth with 12.16.2. ¯\_(ツ)_/¯

**Comment by nmammeri** [comment]
I got into this problem on Ubuntu 18. node was installed using snap.
Got it working working by installing node using nvm:
sudo snap remove node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
restart terminal to load nvm
nvm install v12.16.3
npx create-nuxt-app my-app

I'm not 100% sure but I think the node snap package tries to install node_gyp c++ module and some C++ compilation problems occur. That's why some people reported that it works when installing g++.

Hope this can help somebody

**Comment by PedroJuan91** [comment]
> I got into this problem on Ubuntu 18. node was installed using snap.
> Got it working working by installing node using nvm:
> sudo snap remove node
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
> restart terminal to load nvm
> nvm install v12.16.3
> npx create-nuxt-app my-app
> 
> I'm not 100% sure but I think the node snap package tries to install node_gyp c++ module and some C++ compilation problems occur. That's why some people reported that it works when installing g++.
> 
> Hope this can help somebody

the problem lies at the snap package at nodejs. I tried to reinstall nodejs and use ppa as a source of version >> https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04. And the installation somehow works. :)

**Comment by octojoerg** [comment]
> I got into this problem on Ubuntu 18. node was installed using snap.
> Got it working working by installing node using nvm:
> sudo snap remove node
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
> restart terminal to load nvm
> nvm install v12.16.3
> npx create-nuxt-app my-app
> 
> I'm not 100% sure but I think the node snap package tries to install node_gyp c++ module and some C++ compilation problems occur. That's why some people reported that it works when installing g++.
> 
> Hope this can help somebody

Huge thanks, worked for me! I installed node initially via "Ubuntu-Software". This caused the problem. After uninstalling node with `sudo snap remove node`, [installing node with NVM](https://phoenixnap.com/kb/update-node-js-version) and updating NPM to latest version the problem was solved.

**Comment by munkhbaatar999** [comment]
Thanks for your effort. I am gonna try this.

**Comment by CodeChari** [comment]
> I got into this problem on Ubuntu 18. node was installed using snap.
> Got it working working by installing node using nvm:
> sudo snap remove node
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
> restart terminal to load nvm
> nvm install v12.16.3
> npx create-nuxt-app my-app
> 
> I'm not 100% sure but I think the node snap package tries to install node_gyp c++ module and some C++ compilation problems occur. That's why some people reported that it works when installing g++.
> 
> Hope this can help somebody

It works, I had installed the node using snap(the problem seems to be with snap), I updated the node using apt and now everything works fine!
[https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version]
