### ISSUE TITLE
Cannot create nuxt-app using yarn 1.13.0

### ISSUE THREAD

**Issue by ZainW** [nuxt/create-nuxt-app#188]
Hi there, with the current create-nuxt app (2.4.2) is does not seem possible that I can create a project from scratch using yarn. I tried the below code and `yarn create nuxt-app nuxttest` same errors as shown below

If I can provide any other relevant information let me know. there was no template for issues. Can definitely be a yarn bug but i ran `yarn create react-app` with 0 issues

```sh
yarn create nuxt-app
yarn create v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@vue/cli > @vue/cli-ui > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "@vue/cli > @vue/cli-ui > graphql-type-json@0.2.1" has unmet peer dependency "graphql@>=0.8.0".
[4/4] 🔨  Building fresh packages...

success Installed "create-nuxt-app@2.4.2" with binaries:
      - create-nuxt-app
env: node\r: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-nuxt-app
Arguments:
Directory: /Users/zain/projects
Output:
```

note: runs as expected using the equivalent `npx` based command

**Comment by manniL** [comment]
Can second that.

**Comment by zebamba** [comment]
I am having the same issue.

**Comment by joemirizio** [comment]
It looks like `/usr/local/bin/create-nuxt-app` has DOS line endings. A `dos2unix` keeps getting overridden by `yarn create nuxt-app`

**Comment by clarkdo** [comment]
Could you try 2.4.3 ?

**Comment by manniL** [comment]
Fixed, thanks :relaxed:

**Comment by jay8t6** [comment]
I am on 2.5.0, still running into the same issue

**Comment by clarkdo** [comment]
Will have a look now

**Comment by ZainW** [comment]
can confirm same issue as previously stated in OP on current version (2.5.0)

**Comment by clarkdo** [comment]
I’ll publish a patch release in 1 hour

**Comment by clarkdo** [comment]
@jay8t6 @ZainW Could you please verify 2.5.1 and close the issue if it's fixed

**Comment by ZainW** [comment]
works for me!
thanks again

out of curiosity why did the bug pop back in? something git flow related?

**Comment by clarkdo** [comment]
A CRLF issue when publishing under windows , sorry for the inconvenience

**Comment by jay8t6** [comment]
Thanks! Much appreciated!


Sent from Yahoo Mail for iPhone


On Wednesday, March 6, 2019, 2:20 PM, Xin Du (Clark) <notifications@github.com> wrote:


A CRLF issue when publishing under windows , sorry for the inconvenience
