### ISSUE TITLE
404 - This page could not be found

### ISSUE THREAD

**Issue by lucasfontesgaspareto** [nuxt/create-nuxt-app#19]
I'm create a nuxt app with settings below
 - No backend framework
 - Vuetify
 - No axios
 - ESLint

and every page when that i'm access show in log this message: `{ statusCode: 404, message: 'This page could not be found' }`. I wanna to know where and why this message is outputted.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c12">#c12</a>)</em></sub></div>

**Comment by aldarund** [comment]
This should be obsolete.
