### ISSUE TITLE
nuxt build doesn't minify css

### ISSUE THREAD

**Issue by amitgur** [nuxt/create-nuxt-app#201]
Hello

I'm a beginner in nuxt. I'm using vuetify+express out of the box setup. running nuxt build and nuxt start, my output css is not minified.

Any hint with that? 
my production site https://shiru.me

Thanks

**Comment by clarkdo** [comment]
@amitgur Could you please provide more details about which part of css is not minified, because I can see minified in the link you provided.
![image](https://user-images.githubusercontent.com/4312154/53891758-f2ea0700-4022-11e9-8f4c-2fe0cc67203f.png)

**Comment by amitgur** [comment]
This is the source for production as seen from the client side
![image](https://user-images.githubusercontent.com/4021701/53894888-93e3bc80-4039-11e9-8e79-cd7c107905a3.png)
and it goes like this till line 643. I'm not using postcss. 
Thank you @clarkdo

**Comment by clarkdo** [comment]
This style is from vuetify, you can refer its [doc](https://vuetifyjs.com/en/framework/theme#minification) for minification

**Comment by amitgur** [comment]
Thank you @clarkdo
