### ISSUE TITLE
Adonis commands always running nuxt build

### ISSUE THREAD

**Issue by samturrell** [nuxt/create-nuxt-app#208]
Due to the service provider running the Nuxt builder on boot it's running even when other adonis commands are run.

In laravel you'd get around this by checking if it's being run in the console, but as everything in node is via the console that approach won't work.

Maybe we could check if the `index.js` is being referenced in the `argv`?

Happy to submit a PR if you can think of a better solution.

**Comment by faiyaz26** [comment]
I am facing same problem, any quick fix?

**Comment by faiyaz26** [comment]
Oh, solved this problem by using this helper from Adonis: https://adonisjs.com/docs/4.0/helpers#_isacecommand
