### ISSUE TITLE
Old version with create-nuxt-app command

### ISSUE THREAD

**Issue by OndrejCibulka** [nuxt/create-nuxt-app#209]
Hello everybody,

I am downloading new nuxt project, but i noticed, that in packages.json is nuxt in version 1.0.0
`"dependencies": {
    "nuxt": "^1.0.0"
  },`

Is this supposed to be like this, when latest nuxt version is 2.5.1?

Thank you.

**Comment by manniL** [comment]
Your create-nuxt-app version might be outdated.

**Comment by OndrejCibulka** [comment]
That was it, thank you!

**Comment by MartCube** [comment]
how do you update create-nuxt-app ? 
I get 2.4 version when i make new project

**Comment by manniL** [comment]
Once again. `^2.4.0` matches anything between 2.4.0 and < 3.0.0 (so all minor or patch versions based on 2.x)

**Comment by jackiboy** [comment]
> how do you update create-nuxt-app ?
> I get 2.4 version when i make new project

@MartCube if you go like this it will install Nuxtjs 2.x instead of 1.x
`npx create-nuxt-app@^2.4.0 your-app-name`

**Comment by Tweakings** [comment]
How exactly does one go about "updating create-nuxt-app". I was under the assumption it gets the latest package before executing? I'm struggling to find anything related to updating an npx package? I'm stuck creating apps with nuxt v1.

**Comment by begueradj** [comment]
> That was it, thank you!

Could you please share how you upgraded this mysterious `create-nuxt-app` ?

**Comment by princebatey** [comment]
How everyone how you i open an existing nuxt.js to my brownser and how can i get back to an old version of nuxt ?
