### ISSUE TITLE
nuxt初始化时提示：No matching version found for node-releases@^1.1.13

### ISSUE THREAD

**Issue by lk8888** [nuxt/create-nuxt-app#214]

**Comment by clarkdo** [comment]
@lk8888 你好， 能否提供一下详细的重现步骤和版本号？

**Comment by lk8888** [comment]
你好，我之前用npm安装插件就会报这个错，也试过更新node和npm版本，没有解决，后来我改用yarn安装没有问题，今天我再去重新用npm安装，发现已经没有这个问题了

**Comment by lk8888** [comment]
> @lk8888 你好， 能否提供一下详细的重现步骤和版本号？
你好，我之前选择用npm包会有这个问题，试着更新node和npm版本，没有解决，就选择用yarn是没有问题的，今天再去选择用npm，发现已经没有这个问题了

**Comment by lk8888** [comment]
@clarkdo 你好，我之前选择用npm包会有这个问题，试着更新node和npm版本，没有解决，就选择用yarn是没有问题的，今天再去选择用npm，发现已经没有这个问题了
