### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by AlamTheInnov** [nuxt/create-nuxt-app#215]
Installing fresh nuxt app, i am getting this after running localhost:3000 only if i choose custom UI frameworks is bootstrap! 

Cannot read property 'extend' of undefined
node_modules\bootstrap-vue\es\components\button\button-close.jsopen in editor
    }
  } // @vue/component

};

var _default2 = _vue.default.extend({
  name: NAME,
  functional: true,
  props: props,
  render: function render(h, _ref) {
    var props = _ref.props,
                 
Js
@35:30

**Comment by allon-z** [comment]
I was also getting this issue when adding the bootstrap on the new app. For some reason when my new project was created using **yarn create nuxt-app**, the bootstrap was not working. I tried creating it with **npx create-nuxt-app** and it worked fine. Not sure if that is helpful, but that was my experience!

**Comment by AlamTheInnov** [comment]
@allon-z thanks for your comment, Actually in my case its not working using npx create-nuxt-app app-name

**Comment by clarkdo** [comment]
@AlamTheInnov Thanks for the reporting.

This bug has been fixed in bootstrap-vue, more details: https://github.com/bootstrap-vue/bootstrap-vue/issues/3038
