### ISSUE TITLE
nuxt page routes are not getting rendered (404 error)

### ISSUE THREAD

**Issue by madrus** [nuxt/create-nuxt-app#220]
I have seen a somewhat similar issue #138 but I am not using Express but have chose for a Universal flavour. I have posted my project on Github: [finadmin4u](https://github.com/madrus/finadmin4u.git). This is a simple website with just four links: "/", "/about", "/projects", and "/contact".
Here are my findings:
1. `yarn build ` followed by `yarn start` works fine and I can navigate between all links as expected
2. `yarn generate` and publish to Netlify works fine as well when published. see [here](https://vigorous-mcnulty-d40c41.netlify.com/).
However:
3. `yarn dev` does **NOT** generate the "/about", "/projects", and "/contact" pages.

**Comment by manniL** [comment]
Can't repro:

https://codesandbox.io/s/github/madrus/finadmin4u

**Comment by madrus** [comment]
@manniL Not sure what you have checked. I see it works in the CodeSandbox. However, my issue is that the **development mode** does not work locally if running `yarn dev`. Have you actually tried to clone the repo and then run `yarn && yarn dev`?

**Comment by manniL** [comment]
@madrus the codesandbox is actually doing `yarn dev`.

**Comment by manniL** [comment]
Also:

![image](https://user-images.githubusercontent.com/640208/56499713-da1cae80-6507-11e9-92bb-a61c09198e2b.png)

**Comment by madrus** [comment]
OMG, thanks for letting me know. That basically means there is something wrong with my machine. Glad it was not a bug in Nuxt. :P)

**Comment by madrus** [comment]
I have new information. `yarn dev` works fine in Firefox and in Safari. The described issue happens only in Chrome:
<img width="307" alt="error" src="https://user-images.githubusercontent.com/7058116/56513230-149b4100-6532-11e9-8913-cea47721f591.png">
Not sure if it is a Nuxt issue as Chrome can be full of surprises.

**Comment by manniL** [comment]
Strange 🤔 
Latest chrome version?

**Comment by madrus** [comment]
> Latest chrome version?
Yes, sure. Google Chrome keeps itself automagically updated.

**Comment by madrus** [comment]
Got it! It is definitely Google Chrome. If running in the normal mode. Once I tried to open the same URL in Chrome Incognito Mode, everything started working as expected.
