### ISSUE TITLE
use elementUI to init nuxt-app catch error : ELEMENTHTML is not define

### ISSUE THREAD

**Issue by upeartaker** [nuxt/create-nuxt-app#222]

**Comment by upeartaker** [comment]
修改错别字

**Comment by Yangshisan** [comment]
Me,too

**Comment by LeanderY** [comment]
Me,too

**Comment by LeanderY** [comment]
删除 element-ui.common.js 中的 scrollContainer: [String, HTMlement] 这行代码就行了

**Comment by upeartaker** [comment]
> 删除 element-ui.common.js 中的 scrollContainer: [String, HTMlement] 这行代码就行了

Thanks,i will try again

**Comment by ClassName** [comment]
> 删除element-ui.common.js中的scrollContainer：[String，HTMlement]这行代码就行了

这个不是在npm包里的东西吗，删除后重新npm还会出现鸭

**Comment by ClassName** [comment]
我也碰到这个问题了

**Comment by upeartaker** [comment]
> 我也碰到这个问题了

我今天上午还没有这个问题，后天配了一些其他的module把项目搞崩了，再安装就一直报错了

**Comment by aldarund** [comment]
Its a problem in element ui -> https://github.com/ElemeFE/element/issues/15261

**Comment by Yangshisan** [comment]
I use element-ui@2.4.1

**Comment by aldarund** [comment]
@Yangshisan if you have in your package.json ^2.4.11 than a latest one will be installed .  See https://semver.org/
