### ISSUE TITLE
HTMLElement is not defined 创建项目之后无法运行？

### ISSUE THREAD

**Issue by grace618** [nuxt/create-nuxt-app#223]
初始化选择 KOA /Element UI/axios/eslint/prettier
![2019-04-28_152141](https://user-images.githubusercontent.com/19409528/56860505-e56d4f80-69c9-11e9-909e-862d7fcf7713.png)
![2019-04-28_152622](https://user-images.githubusercontent.com/19409528/56860517-ffa72d80-69c9-11e9-9b38-81f3e07f6a80.png)
![2019-04-28_152723](https://user-images.githubusercontent.com/19409528/56860533-25cccd80-69ca-11e9-981c-8513ef3e2cbb.png)

**Comment by qykingle** [comment]
后来怎么解决的？

**Comment by grace618** [comment]
@qykingle 其中有一个issues问到了，是element ui的问题，element 说下次版本会修复，可以试试其他ui框架，我试了iview可以

**Comment by ndphuong** [comment]
How about this issue ?
