### ISSUE TITLE
Update Tailwind.

### ISSUE THREAD

**Issue by MichMich** [nuxt/create-nuxt-app#242]
A few weeks ago Adam Wathan released Tailwind 1.0. `create-nuxt-app` still includes the config files for an old setup: https://github.com/nuxt/create-nuxt-app/tree/master/template/frameworks/tailwind

It is advised to upgrade to Tailwind ^1.0

**Comment by manniL** [comment]
See https://github.com/nuxt/create-nuxt-app/pull/237
