### ISSUE TITLE
Next Release with updated Hapi Nuxt plugin

### ISSUE THREAD

**Issue by iniva** [nuxt/create-nuxt-app#245]
Current release `v2.6.0` uses `hapi-nuxt: ^1.0.1` which still uses [hapi v17](https://github.com/nuxt-community/hapi-nuxt/blob/v1.0.0/package.json#L23). 

Creating a new app using `yarn create nuxt-app example` and choosing **hapi** as server makes the installation show lots of warnings like this:
```
warning hapi-nuxt@1.0.1: Please use @nuxtjs/hapi
warning hapi-nuxt > hapi@17.8.5: This module has moved and is now available at @hapi/hapi. Please update your dependencies as this version is no longer maintained an may
 contain bugs and security issues.
```

The code in `master` branch has the latest `hapi-nuxt` version along with other [enhancements](https://github.com/nuxt/create-nuxt-app/compare/v2.6.0...master) 

Can you publish the next release?

**Comment by pi0** [comment]
#231 is not published yet. You can safely do this in your project.

**Comment by clarkdo** [comment]
v2.7.1 has been released
