### ISSUE TITLE
Error after setup - Unexpected identifier - Missing stack frames

### ISSUE THREAD

**Issue by mistGit** [nuxt/create-nuxt-app#246]
![Screenshot_2019-05-27 Screenshot](https://user-images.githubusercontent.com/34454110/58398481-767d2800-8055-11e9-8979-03b755b22d30.png)

Getting this error after setup using "npx create-nuxt-app"

Versions:
Nuxt: tried both 2.7.1 & edge(2.8.0)
Npm: 6.4.1
Node: 10.15.3 (Also tried reinstalling...)

No additional modules installed.

Options selected when installing:
Server: None
UI Framework: Bootstrap
Testing framework: None
Nuxt mode: Universal
Added Axios

Any ideas on how to fix this issue?
I tried to look around for similar issues, but none of them seemed related to me. 
Sorry if this thread is a duplicate of another one. I just still haven't managed to figure this out yet.

**Comment by nderewianka** [comment]
try running 'npm run generate' and then 'npm run dev'

**Comment by mistGit** [comment]
@nderewianka Unfortunately it had no effect. 

Interesting thing is that when I build it for production and run it after that, it works,

**Comment by bryan-22** [comment]
still having the same problem. do you slve it?

**Comment by noven** [comment]
It's the bootstrap-vue that cause the problem.
In nuxt.config.js , under modules remove 'bootstrap-vue/nuxt'. 

then create BootstrapVue.js under folder plugins. 
`import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)
`

Back to nuxt.config.js, and register the plugins manually

`  plugins: [
    'plugins/BootstrapVue'
  ],`

**Comment by mistGit** [comment]
@noven Thanks a lot! This solution got it working!
