### ISSUE TITLE
I don't see ant-design?

### ISSUE THREAD

**Issue by kacak9229** [nuxt/create-nuxt-app#249]
Can you guys update so that I can use ant-design

my npm/npx is 6.9

**Comment by clarkdo** [comment]
Could you try v2.7.1 ?
![image](https://user-images.githubusercontent.com/4312154/59102339-acf35680-8923-11e9-969c-7a1463ee296f.png)

**Comment by kacak9229** [comment]
How do i update to 2.7.1?

Regards,

**Comment by clarkdo** [comment]
Which tool are you using with crate-nuxt-app ?

If you are not using specific version on `create-nuxt-app`, latest version will be automatically applied.

https://github.com/nuxt/create-nuxt-app#usage

**Comment by kacak9229** [comment]
I upgraded my npm by running npm update and I still get the nuxt 2.0.0

I use npx create-nuxt-app <app_name>

I even did `npm update create-nuxt-app -g`

How do I update it??

**Comment by clarkdo** [comment]
nuxt@^2.0.0 is correct, it will map to latest Nuxt 2.x

Have tried pressing down arrow in UI choices ? `ant-design` is at the bottom as my screenshot above.

**Comment by kacak9229** [comment]
Hey thanks for helping me, but the problem still persist . I tried to move the arrow down

<img width="379" alt="Screenshot 2019-06-11 at 12 27 21 AM" src="https://user-images.githubusercontent.com/2588948/59210252-c3c5d180-8bdf-11e9-9549-9ada5fd9f91b.png">

My npm version is 6.9.0

My package.json

<img width="440" alt="Screenshot 2019-06-11 at 12 31 29 AM" src="https://user-images.githubusercontent.com/2588948/59210524-5ebeab80-8be0-11e9-9161-6b9bd804a7ce.png">

**Comment by clarkdo** [comment]
It should be after buefy, as well as iview.

**Comment by manniL** [comment]
probably a cached or globally installed version of create-nuxt-app?

**Comment by kacak9229** [comment]
Its not after buefy. It is not there. How do i unistall create-nuxt-app? probably it is a cached thing

**Comment by kacak9229** [comment]
Can anyone help over here?

**Comment by clarkdo** [comment]
@kacak9229 It’s quite difficult to figure out you issue without a reproducible description, could you please join the nuxt discord so that we can communicate without any delay?
