### ISSUE TITLE
Very bad performance from Audit (Lighthouse from Google)

### ISSUE THREAD

**Issue by kacak9229** [nuxt/create-nuxt-app#257]
Im doing a benchmarking to see the performance of nuxt application. It is really bad, I did it many times but always getting bad result

<img width="1322" alt="Screenshot 2019-06-13 at 4 29 33 PM" src="https://user-images.githubusercontent.com/2588948/59416877-cf401500-8df8-11e9-87b4-f8ab955b6eb7.png">

<img width="1398" alt="Screenshot 2019-06-13 at 4 29 39 PM" src="https://user-images.githubusercontent.com/2588948/59416876-cf401500-8df8-11e9-8e4a-c18d4c647534.png">

**Comment by jpsc** [comment]
Hello @kacak9229,

That can be for a miriad of reasons. Not necessarily a nuxt template problem.
But I actually see that you have a vendors file that is 5Mb with a total of 7Mb download. I think that's your main culprid for that performance problem.

You can use `nuxt build -a` to check your bundle contents.

**Comment by manniL** [comment]
Make sure to not test against the dev build but the prod version ☺️
