### ISSUE TITLE
outdated package.json

### ISSUE THREAD

**Issue by tiagomatosweb** [nuxt/create-nuxt-app#258]
Hi, when create a fresh new nuxt app via

```
yarn create nuxt-app <project-name>
```

the package json seems to show the wrong version of the packages.

For instance:
```
"dependencies": {
    "nuxt": "^2.0.0"
  },
```

Which currently is 2.8.1

**Comment by jpsc** [comment]
Hello @tiagomatosweb.

I don't think it's a problem because the `^` is there to ensure you get the latest minor version.

**Comment by tiagomatosweb** [comment]
Certainly @jpsc but it is annoying see the wrong version of packages, not just for nuxt.
Anyway ...

**Comment by manniL** [comment]
Constraints in package.json !== actual version number.
