### ISSUE TITLE
New project with ESLint/Prettier, warnings and errors

### ISSUE THREAD

**Issue by Extarys** [nuxt/create-nuxt-app#274]
I just run the create-nuxt-app and I checked ESLint and Prettier and right of the bat I have those errors.
Is it normal? Am I missing something?

I searched here, I'm sorry if I missed an answer.

```
 ERROR  in ./pages/index.vue                                                       friendly-errors 21:04:29

Module Error (from ./node_modules/eslint-loader/index.js):                         friendly-errors 21:04:29

/media/DarkHawk/srv/NodesProjects/NJS-domains/pages/index.vue
  5:25  warning  Expected 1 line break after opening tag (`<h1>`), but no line breaks found                                                                                                                                                                        vue/singleline-html-element-content-newline
  5:36  warning  Expected 1 line break before closing tag (`</h1>`), but no line breaks found                                                                                                                                                                      vue/singleline-html-element-content-newline
  6:28  warning  Expected 1 line break after opening tag (`<h2>`), but no line breaks found                                                                                                                                                                        vue/singleline-html-element-content-newline
  6:55  warning  Expected 1 line break before closing tag (`</h2>`), but no line breaks found                                                                                                                                                                      vue/singleline-html-element-content-newline
  8:76  error    Replace `>Documentation</a` with `⏎··········>Documentation</a⏎········`                                                                                                                                                                          prettier/prettier
  9:11  error    Replace `·href="https://github.com/nuxt/nuxt.js"·target="_blank"·class="button--grey">GitHub</a` with `⏎··········href="https://github.com/nuxt/nuxt.js"⏎··········target="_blank"⏎··········class="button--grey"⏎··········>GitHub</a⏎········`  prettier/prettier

✖ 6 problems (2 errors, 4 warnings)
  2 errors and 4 warnings potentially fixable with the `--fix` option.

                                                                                   friendly-errors 21:04:29
 @ ./.nuxt/router.js 13:24-15:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

**Comment by clarkdo** [comment]
This should be fixed in next version

**Comment by Extarys** [comment]
Thanks @clarkdo.
I activated fixing on save, but after modification the changes rolls back. Is it a configuration file missing for prettier/eslint in the folder? Or is it my settings in VS Code that can mess with this?

**Comment by clarkdo** [comment]
It’s because the default templates were not well formatted, now the template files are all formatted in create-nuxt-app repo.

**Comment by Extarys** [comment]
Ohh I see, is there a way to test that? You said it was going to be in the next release?
I could never make prettier and vue work ok together I don't know why and I'm kind of lost on how to fix this :smile:

**Comment by clarkdo** [comment]
The prettier formatting on save should work together with your vscode plugin setting, you should check the doc of the plugin you’re using.

**Comment by Extarys** [comment]
Oh ok awesome, thanks!

**Comment by Extarys** [comment]
Well, I have prettier and vetur installed. It doesn't seem that there is an option for "Read the config file provided inside the project's folder" kind of thing.

Even `yarn run lint -- --fix` messed up and made things worse.

I thought the plugins read the config files `.prettierrc` and `.eslingrc.js` provided by create-nuxt-app... :confused:

**Comment by clarkdo** [comment]
Can you provide me a repo and steps?

I can have a look tmr, it’s 1 am now😿

**Comment by Extarys** [comment]
Oh damn, go get some sleep :)

**Comment by Extarys** [comment]
Ok, it's VS Code the problem. Creating a new project and running it is fine. But when I open the folder in VS Code and try to run it there is plenty of errors. I think a plugin is messing the code. I should've test this earlier.

Have a good night and thanks for your help

**Comment by Extarys** [comment]
I modified .eslintrc.js:
```
extends: [
    'prettier',
    'prettier/vue',
    '@nuxtjs',
    'plugin:nuxt/recommended',
    'plugin:vue/essential',
    'eslint:recommended'
  ],
```

VS Code extentions: Vetur, Eslint.
Config:
```
{
  "editor.formatOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.autoFixOnSave": true,
  "eslint.packageManager": "yarn",
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  "[vue]": {
    "editor.formatOnSave": false
  }
}
```

TADA! :fireworks:

**Comment by wuhhh** [comment]
Installing Nuxt without eslint & prettier and following the steps here https://medium.com/@gogl.alex/how-to-properly-set-up-eslint-with-prettier-for-vue-or-nuxt-in-vscode-e42532099a9c gave me a perfect working setup. Hope it helps :)

**Comment by Extarys** [comment]
Thanks @wuhhh

**Comment by vlad-tircomnicu** [comment]
Thank you @wuhhh

**Comment by alansutherland** [comment]
god I hate eslint breaking things

**Comment by DerekHill** [comment]
I recently created a new nuxt app using `npx create-nuxt-app` and got these prettier warnings.

This install included `"eslint-config-prettier": "^4.1.0"` per https://github.com/nuxt/create-nuxt-app/blob/18740f86eb2afd3226d277b42000e6ab21e94deb/template/_package.json#L136

Updating this to eslint-config-prettier to ^6.7.0 seemed to fix the issue.

**Comment by xgqfrms** [comment]
# what's wrong with this?

![image](https://user-images.githubusercontent.com/7291672/70060403-702bc200-161d-11ea-96f0-8ebb7c73a5e8.png)

> how disabled prettier?

**Comment by clarkdo** [comment]
From the console, errors look like related to indentation.

@xgqfrms I'll open a pr to fix this.

**Comment by xgqfrms** [comment]
@clarkdo I think it should be a warning, not an error which will be broken the app, that's not too good for the beginner.

**Comment by clarkdo** [comment]
As I mentioned above, I'll open a pr to fix this, there should have no error in this file 😃

**Comment by rajeshdh** [comment]
Adding  
```
"scripts": {
  "lintfix": "eslint --fix --ext .js,.vue --ignore-path .gitignore ."
}
```
to my `package.json` file fixed it for me.

Now running `npm run lintfix ` fixes all the errors.

**Comment by dosstx** [comment]
The above issue fixed it for me, too. Thanks.

**Comment by baptistecs** [comment]
For me the issue was the VS Code config, I have had to set:
`"vetur.format.defaultFormatter.html": "prettier"`
instead of the default value:
`"vetur.format.defaultFormatter.html": "prettyhtml"`

**Comment by Developer-Rocha** [comment]
@rajeshdh Thanks bro. It's work for me.

**Comment by andriilive** [comment]
Issue appear only on JavaScript Setup
TypeScript seems ok

**Comment by kasvith** [comment]
Still having the issue

**Comment by fabiom91** [comment]
> The prettier formatting on save should work together with your vscode plugin setting, you should check the doc of the plugin you’re using.
> For example editor.formatOnSave in https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

This solved the error for me! Thanks
