### ISSUE TITLE
Initial install with yarn and Vuetify selected gives 6 problems

### ISSUE THREAD

**Issue by MaeseppTarvo** [nuxt/create-nuxt-app#276]
Hey! I wanted to say that Initial install with yarn and Vuetify selected gives 6 problems.
These are the options provided:
```
? Use a custom UI framework vuetify
? Choose rendering mode SPA
? Use axios module NO
? Use eslint YES
? Choose a package manager yarn
```

`VuetifyLogo.vue 6:3  error  Insert `/`  prettier/prettier`
```
index.vue   25:26  error    Insert `⏎············`                               prettier/prettier
  34:30  error    Insert `⏎············`                               prettier/prettier
  43:11  warning  Disallow self-closing on HTML void elements (<hr/>)  vue/html-self-closing
  47:11  warning  Disallow self-closing on HTML void elements (<br/>)  vue/html-self-closing
```
`inspire.vue  4:7  warning  Disallow self-closing on HTML void elements (<img/>)  vue/html-self-closing`

yarn lint --fix fixes it but then again gives error.

**Comment by yli-yasir** [comment]
I am having the exact same issue but with NPM as package manager...

**Comment by aretw0** [comment]
It has been fixed, so... why is still happening?

**Comment by MaeseppTarvo** [comment]
Because the way they "fixed" the problem does not fix the issue. They just moved the line more down so they should not conflict anymore with each other. It should at least fix some of the problems that may occur that are related to similar problems.

**Comment by clarkdo** [comment]
@aretw0 The fix hasn’t been released yet, it will be released before next weekend.

@MaeseppTarvo If you’re interested the background of the fix, you can have a look at https://github.com/prettier/prettier/issues/5363
