### ISSUE TITLE
 <%_ if ( ) { _%>

### ISSUE THREAD

**Issue by selfconfidence** [nuxt/create-nuxt-app#280]
vscode   write nuxt.config.js  <%_ if (eslint) { _%> , error  Tips?

**Comment by selfconfidence** [comment]
我在使用 vscode 编写代码的时候,导入脚本架,但是vs不认账,无法识别 <%_ if ( ) { _%> 这种语法格式,是否需要安装什么插件?

**Comment by clarkdo** [comment]
`<%_ if ( ) { _%> ` 是模版文件, 不能直接倒入到工程, 请按照文档使用https://github.com/nuxt/create-nuxt-app#usage

**Comment by selfconfidence** [comment]
谢谢,明白了.
