### ISSUE TITLE
outdated dependencies in newly created app

### ISSUE THREAD

**Issue by dominikg** [nuxt/create-nuxt-app#287]
```
testapp$ npm outdated
Package                        Current          Wanted         Latest  Location
@nuxtjs/eslint-config            0.0.1           0.0.1          1.0.1  testapp
@nuxtjs/eslint-module            0.0.1           0.0.1          0.2.1  testapp
@nuxtjs/pwa                      2.6.0           2.6.0  3.0.0-beta.16  testapp
babel-core              7.0.0-bridge.0  7.0.0-bridge.0         6.26.3  testapp
eslint                          5.16.0          5.16.0          6.0.1  testapp
eslint-config-prettier           4.3.0           4.3.0          6.0.0  testapp
```
especially babel-core seems odd, as @babel/core exists for quite some time and nuxt.js itself uses it: https://github.com/nuxt/nuxt.js/blob/dev/package.json

Is there a recommended way to update dependencies after the initial creation?

version information:
```
testapp$ node -v
v12.6.0
testapp$ npm -v
6.10.1
testapp$ nuxt -v
@nuxt/cli v2.8.1

testapp$ npx create-nuxt-app 
npx: installed 379 in 13.379s
create-nuxt-app v2.8.0
```

**Comment by clarkdo** [comment]
I'll update them and it should be fixed in next release.

**Comment by miteyema** [comment]
@clarkdo Will this mean that ESLint 6 will be used from now on?

**Comment by clarkdo** [comment]
It depends what https://github.com/nuxt/eslint-config is using

**Comment by mastix** [comment]
Not to forget that nuxt also uses vuetify-loader (1.2.2; latest) which refers to vuetify ^1.3.0 (latest would be 2.0.0).

**Comment by manniL** [comment]
@mastix 	see #297
