### ISSUE TITLE
Add a New UI Framework: Framevuerk

### ISSUE THREAD

**Issue by nainemom** [nuxt/create-nuxt-app#288]
Hi. I fork the repository and put **Framevuerk** into UI Frameworks in a new branch. I check everything to make sure it works (with yarn, other server frameworks, etc). But now I don't found anywhere to verify changes that i made. So can you please check it before I send a pull-request?

forked repo:
https://github.com/framevuerk/create-nuxt-app/tree/add-framevuerk

Framevuerk docs and demo:
https://framevuerk.com

Framevuerk source on github:
https://github.com/framevuerk/framevuerk

**Comment by clarkdo** [comment]
Feel free to create the pr, the team members will help and review
