### ISSUE TITLE
linting doesn't work properly

### ISSUE THREAD

**Issue by sandro-git** [nuxt/create-nuxt-app#290]
hello,

i just start a new project with create-nuxt-app and eslint doesn't work properly with prettier. i can't change the default settings. i use vscode. can you help me ?

sorry guys can someone help me ? the linking it just driving me crazy !!!

**Comment by kakajansh** [comment]
I also had trouble with linting. For my case the reason was that `npx create-nuxt-app` pulls older version of eslint module. Upgrading deps resolved issue.

Details of my issue [here](https://github.com/nuxt-community/eslint-module/issues/12)

**Comment by clarkdo** [comment]
The new version will be released this weekend, the error should be fixed, I'll leave comment here after release.

**Comment by clarkdo** [comment]
v2.9 has been released, could you try it ?

**Comment by sandro-git** [comment]
@clarkdo thank you very much it works just fine. i notice a kind of glitch when linting templates before prettier/prettier take over and format properly. 

thank you very much for this fix. and your time.
