### ISSUE TITLE
Create with Vuetify version 2.0.0 

### ISSUE THREAD

**Issue by appximus** [nuxt/create-nuxt-app#295]
Hi all,

I've been trying to create nuxt application using Vuetify 2.0.0.

I use create-nuxt-app then try to upgrade Vuetify and modify webpack but got nowhere.
I keep getting `sass` and `node-sass` error even though i specifically added 
````
    config.module.rules.push({
        test: /\.s(c|a)ss$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              implementation: require('sass'),
              fiber: require('fibers'),
              indentedSyntax: true // optional
            }
          }
        ]
      })
````

Anyone done this yet?

**Comment by mastix** [comment]
https://github.com/nuxt-community/vuetify-module/issues/66 :)

**Comment by lysz210** [comment]
I upgraded @nuxtjs/vuetify, sass, sass-loader and fibers with yarn and it worked, didn't do any changes. Some componenge are different so I have work to do.
I checked with style[lang=scss scoped] in .vue.

**Comment by SaKKo** [comment]
It seems like my problem is I'm using create-nuxt-app and the default template has errors.

**Comment by bujji1** [comment]
@SaKKo - Did you find any solution for the default template issue ? I am having the same problem

**Comment by milosmijakovac** [comment]
1.0.0-beta is the version of the nuxt-module, and that’s the version that had Vuetify 2.0.0-beta.2 as a dependency

so to be clear: 
when you see in package.json  --->  "@nuxtjs/vuetify": "^1.0.0"  that means that this module has vuetify 2.0.0

if you go into node_modules and find vuetify folder, there is a package.json file where you can see what is current vuetify version.

**Comment by dneeleman** [comment]
> 1.0.0-beta is the version of the nuxt-module, and that’s the version that had Vuetify 2.0.0 as a dependency
> 
> so to be clear:
> when you see in package.json ---> "@nuxtjs/vuetify": "^1.0.0" that means that this module has vuetify 2.0.0
> 
> if you go into node_modules and find vuetify folder, there is a package.json file where you can see what is current vuetify version.

Actually this is v1.9.0 for me.

**Comment by mockingloris** [comment]
> 1.0.0-beta is the version of the nuxt-module, and that’s the version that had Vuetify 2.0.0 as a dependency
> 
> so to be clear:
> when you see in package.json ---> "@nuxtjs/vuetify": "^1.0.0" that means that this module has vuetify 2.0.0
> 
> if you go into node_modules and find vuetify folder, there is a package.json file where you can see what is current vuetify version.

This was a lifesaver. Thanks for pointing that out,
I was just at the edge of frustration... this brought me back :+1:
