### ISSUE TITLE
install with npx create-nuxt-app, always install old version (v2.3.4)

### ISSUE THREAD

**Issue by willi-dev** [nuxt/create-nuxt-app#296]
any suggestion, i install via npx create-nuxt-app, but always v2.3.4 that installed.. 
how to force install to latest version? 

Thanks.

**Comment by clarkdo** [comment]
Per npm doc: By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.

So you can check 2.3.4 has been installed in your local and uninstall it.

**Comment by manniL** [comment]
Duplicate of #209
