### ISSUE TITLE
eslint with prettier isn't working correctly

### ISSUE THREAD

**Issue by Mourdraug** [nuxt/create-nuxt-app#298]
I'm trying to create project with create-nuxt-app and change indentation to tabs. When I add `"useTabs": true` to `.prettierrc` and run lint I correctly get `prettier/prettier` errors, however running lint --fix results in `no-tabs` errors which should be turned off by eslint-prettier-config. Updating all deps gives me the same errors.

**Comment by manniL** [comment]
Duplicate of #290
