### ISSUE TITLE
[Feature Request] Remove nodemon when chose Server framework `none`

### ISSUE THREAD

**Issue by runyasak** [nuxt/create-nuxt-app#307]
Hi, I always use `create-nuxt-app` to initiate my nuxt projects, it helps me convenient.

Normally, I choose sever framework to `None (Recommend)` because I have separated repos with team.
However, I've seen that there will install with `nodemon` which I didn't use it without server. Finally, I uninstall `nodemon` from `node_modules`.

I want to know that is `nodemon` using in any part of nuxt project without server framework? Or, it should be removed from installing.

If you have any ideas or suggestion, please do not hesitate to reply and comment on this issue. 😎

Thank you,
World

-----

Actually, I have try to change and create PR. Unfortunately, I have problem with extra `,` and there makes error on installing. 😂

**Comment by manniL** [comment]
As you see, it's not that easy for the current architecture :see_no_evil:
