### ISSUE TITLE
Lint-staged template incorrect behavior

### ISSUE THREAD

**Issue by basselAhmed** [nuxt/create-nuxt-app#311]
When you choose the lint-staged option, the default template in package.json will be

```json
"lint-staged": {
    "*.{js,vue}": "yarn lint"
  },
```

But the **yarn lint** script actually lints all js and vue files, not just the staged files which is the wanted behavior by that package as found in 

```json
"scripts": {
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore ."
  },
```

It should be changed to 

```json
"lint-staged": {
    "*.{js,vue}": "eslint"
  },
```
That way it'll work only on staged files and user could add **--fix** option to automatically fix the issues if possible.

**Comment by clarkdo** [comment]
Fixed in https://github.com/nuxt/create-nuxt-app/commit/b516d234d733d0b5f2ddf0e1219d4eadef8e9d40
