### ISSUE TITLE
create-nuxt-app -e or --edge doesn't work

### ISSUE THREAD

**Issue by sandro-git** [nuxt/create-nuxt-app#323]
hello , i try to create an app with create-nuxt-app -e or --edge and does the exact same thing if i have not add any flag is it a normal behavior ? i expect other one. if it's a bug i will glad to help and try to make a PR for that but i don't find any step to launch the project localy.

**Comment by clarkdo** [comment]
Hi @sandro-git , when you use --edge or -e, `nuxt-edge` will be installed and used  instead of `nuxt`, this works fine in my local, could you provide more details ?

**Comment by sandro-git** [comment]
Hi @clarkdo i just try to scarfold again a project and all goes ok. Sorry and thanks for your trouble.

**Comment by clarkdo** [comment]
No worries, thanks.
