### ISSUE TITLE
Why did you downgrade to Nuxt.js v.2.0.0 ?

### ISSUE THREAD

**Issue by begueradj** [nuxt/create-nuxt-app#324]
This is rather a question (sorry, I do not see where else to ask it)

Previously, running `create nuxt-app myApp` installs **nuxt v2.4.0** but today for example I noticed you downgraded to **nuxt v2.0.0**.

Can you please explain why ?

Thank you,
Billal BEGUERADJ

**Comment by manniL** [comment]
Duplicate of #209

**Comment by begueradj** [comment]
Thank you @manniL but the question remains because:
1. I did not change the development environment, so noticing Nuxt is downgraded is weird to me.
2. On the link you provided, there is not an answer to how to upgrade  `nuxt-app`

**Comment by mapsgeek** [comment]
why the hell no one gives a valid explanation ?!!
