### ISSUE TITLE
Unepected Nuxt downgraded version

### ISSUE THREAD

**Issue by begueradj** [nuxt/create-nuxt-app#325]
Previously, running `yarn create nuxt-app myApp` installs Nuxt v2.4.0 but today for example I noticed you downgraded to Nuxt v2.0.0. I did not change the development environment so I can not understand this behavior.

[This](https://github.com/nuxt/create-nuxt-app/issues/324) and [that](https://github.com/nuxt/create-nuxt-app/issues/209) do not provide any clarification to this issue.

Can you please explain why ?

Thank you,
Billal BEGUERADJ

**Comment by manniL** [comment]
Can't reproduce. If you are referring to the `package.json`, please read [my comment](https://github.com/nuxt/create-nuxt-app/issues/209) where I've sent you before.

![image](https://user-images.githubusercontent.com/640208/63218148-bb949000-c154-11e9-94c7-94ef8d90d20b.png)
