### ISSUE TITLE
How does create-nuxt-app function ?

### ISSUE THREAD

**Issue by begueradj** [nuxt/create-nuxt-app#326]
How to check which `create-nuxt-app` version I am running ?
How to upgrade it ?
How to install it ?

I am asking following the answers given [here](https://github.com/nuxt/create-nuxt-app/issues/209) and [there](https://stackoverflow.com/questions/55691937/why-does-create-nuxt-app-installs-nuxt-version-1-4-5?noredirect=1&lq=1).

Thank you,
Billal BEGUERADJ

**Comment by manniL** [comment]
You see the version when using `yarn create nuxt-app`. if it is outdated, clear your yarn/npm cache or remove local versions of it. Please consult the npm/yarn documentation for that.

![image](https://user-images.githubusercontent.com/640208/63218159-0b735700-c155-11e9-889b-1430efd07e7a.png)
