### ISSUE TITLE
devModules still in the 2.9.1 nuxt.config

### ISSUE THREAD

**Issue by TariikHr** [nuxt/create-nuxt-app#329]
I Know that it's easy to change devModules to buildModules in the nuxt.config but i wanted to let you know that even with the latest version of Nuxtjs there is no buildModules in the the nuxt.config and still getting WARNING in the Bash about deprecated devModules

**Comment by clarkdo** [comment]
Thanks for reporting the issue, fixed in create-nuxt-app@2.10.0
