### ISSUE TITLE
Server Rendered Deployment (Universal)

### ISSUE THREAD

**Issue by mjbates7** [nuxt/create-nuxt-app#33]
Hi, had a look around at the issues/documentation, but couldn't find anything specific to my question:

What do we need to deploy to our server to run it in Server Rendered Deployment (Universal)?

image
![image](https://user-images.githubusercontent.com/4522738/36202685-bd9dc6f2-117c-11e8-8fdc-36eedcd36b79.png)

Does this whole folder have to be deployed to the server for it to work (seems quite a lot if we have to upload all the source code to the server), or do we need to just deploy the .nuxt folder?

Any help/how it's meant to be done would be appreciated :)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c18">#c18</a>)</em></sub></div>

**Comment by codeitlikemiley** [comment]
i suggest add .gitignore for dist and .nuxt...
dist folder is for static pages which you might to use with netflix

if you need to run on your server with nodejs
as a universal app
you need to clone your project
do npm install
to install all dependencies
and do npm build to create the .nuxt folder
of course you need to run a web server such as nginx to proxy your request
on localhost:3000 to the domain name you want to redirect...
 
hope this might help

**Comment by Blemming** [comment]
Nuxt has updated their documentation with 
![image](https://user-images.githubusercontent.com/12241815/71039337-e9351a00-20f1-11ea-9497-008112b1e591.png)
Should we be building in development ? Given the build dependencies are installed in the dev depencies ( even when choosing universal app ) Does it make more sense to build on the development machine ?
