### ISSUE TITLE
Trace: Error: Cannot find module './prompts'

### ISSUE THREAD

**Issue by roshangara** [nuxt/create-nuxt-app#350]
after `yarn create nuxt-app auth`
error : 
`Trace: Error: Cannot find module './prompts'`

**Comment by DivvyByZero** [comment]
Getting the same issue with both `npx create-next-app <name>` and `npm init nuxt-app <name>`
Using Windows, node version 12.3.1 and npm 6.9.0

**Comment by padri-zan** [comment]
same problem with npx installation,

> create-nuxt-app v2.11.0
> ✨  Generating Nuxt.js project in multiberkah
> Trace: { Error: Cannot find module './prompts'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\Users\Ps21\AppData\Roaming\npm-cache\_npx\2264\node_modules\create-nuxt-app\saofile.js:9:12)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
>     at sao.run.catch (C:\Users\Ps21\AppData\Roaming\npm-cache\_npx\2264\node_modules\create-nuxt-app\cli.js:46:17)

**Comment by roshangara** [comment]
> Same issue #349
> I recommend using the previous version until this issue is fixed

how?

**Comment by wmartins** [comment]
@roshangara: https://github.com/nuxt/create-nuxt-app/issues/349#issuecomment-536609437

```
npx create-nuxt-app@2.10.1 target-directory
```

**Comment by sebaveg** [comment]
Yesterday I ran npx create-nuxt-app and it worked. Today not. Thanks @wmartins

**Comment by aslamdoctor** [comment]
Same issue here.

**Comment by webcoderkz** [comment]
Just faced this issue:

```
node -v
v12.10.0
npm -v
6.10.3
```

**Comment by baladmsinfo** [comment]
npx create-nuxt-app project-name works yesterday but getting below issue today
Trace: { Error: Cannot find module './prompts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)

**Comment by ghenry** [comment]
Same on Linux here. Will do https://github.com/nuxt/create-nuxt-app/issues/350#issuecomment-536616454

**Comment by aldarund** [comment]
fixed in 2.11.1 https://github.com/nuxt/create-nuxt-app/pull/352

**Comment by ghenry** [comment]
Worth the wait for npm to update or use 2.10.1? Thanks!

**Comment by aslamdoctor** [comment]
Do `npm update -g create-nuxt-app` and then try, it should fix. Worked for me.
