### ISSUE TITLE
pristine app from create-nuxt-app fails on server boot

### ISSUE THREAD

**Issue by perezd** [nuxt/create-nuxt-app#355]
What I ran:
```
npx create-nuxt-app
npx: installed 344 in 11.885s

create-nuxt-app v2.11.1
✨  Generating Nuxt.js project in .
? Project name test
? Project description My stupendous Nuxt.js project
? Author name foo
? Choose the package manager Npm
? Choose UI framework Vuetify.js
? Choose custom server framework Express
? Choose Nuxt.js modules (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Choose linting tools (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Choose test framework Jest
? Choose rendering mode Universal (SSR)
? Choose development tools (Press <space> to select, <a> to toggle all, <i> to invert selection)
```

```
node --version
v12.10.0
```

```
npm --version
6.10.3
```

![](https://media.discordapp.net/attachments/473406004751499275/628986807966498827/unknown.png)

**Comment by VPetar** [comment]
The issue is not in the `create-nuxt-app`. It is in the `nuxt` v2.10.0 released today.

Try setting the version of nuxt to 2.9.0 in the dependencies in your `package.json` file:

```
  "dependencies": {
    ***
    "nuxt": "2.9.0",
    ***
  }
```

I'm sure devs will throw the patch for `nuxt` package soon, but as I said, it's not the `create-nuxt-app` issue.

**Comment by perezd** [comment]
Excellent, I've filed a bug with nuxt.js and attempted your workaround, confirmed its working as expected. Thanks!

**Comment by VPetar** [comment]
> Excellent, I've filed a bug with nuxt.js and attempted your workaround, confirmed its working as expected. Thanks!

You're welcome. Hope it doesn't block you on your endeavors, I'm subbed to the issue you opened on nuxt repo. Thanks.
