### ISSUE TITLE
TypeError: Cannot read property name 'keyName' of undefined

### ISSUE THREAD

**Issue by tabishiqbal** [nuxt/create-nuxt-app#356]
Running into a problem when creating a new app using `yarn create nuxt-app`.  Following were selected from the questions:

1. Server framework: **None (default)**
2. UI Framework:  **Vuetify**
3. Test framwork:  **Jest**
4. Rendering Mode - **Server Side Rendering (Universal)**
5. Modules: **Axios and PWA**
6. Linting Tools: **ESLint & Prettier**
7. Package manager: **yarn**
8. Development tools: **jsconfig**

After setup is completed and you run the server `yarn run dev` the follow error shows up in the console and nothing displays in the browser. However, when I use the same settings except pick Tailwind CSS as the UI framework instead of Vuetify everything works.

Nuxt version: 2.10
Yarn version: 1.19.0
Node version: 10.16.2
Npm version: 6.9.0

![nuxt-vuetify](https://user-images.githubusercontent.com/2093790/66081464-01a38880-e536-11e9-98a8-d6b494b01568.png)

**Comment by reireias** [comment]
I tried some versions in same setting.

2.8.0: ok
2.9.2( and higher): ng

**Comment by byukend-tr** [comment]
Downgrade Nuxt to version 2.9.2 (npm i  --save nuxt@2.9.2)
I think there is some problem about nuxt 2.10.x and @nuxtjs/vuetify

**Comment by shoichiaizawa** [comment]
I downgraded `nuxt` from `2.10.0` to `2.9.2` and it works as expected (I suppose).

![image](https://user-images.githubusercontent.com/1571648/66110992-df2b7100-e602-11e9-947b-4c8c358d450d.png)

FYI, here are the options I selected through the initial setup:

```
? Choose the package manager Yarn
? Choose UI framework Vuetify.js
? Choose custom server framework None (Recommended)
? Choose Nuxt.js modules Axios
? Choose linting tools ESLint, Prettier, Lint staged files
? Choose test framework Jest
? Choose rendering mode Single Page App
? Choose development tools jsconfig.json (Recommended for VS Code)
```

With the following versions:

- Nuxt version: 2.9.2
- Yarn version: 1.19.0
- Node version: 10.16.3
- Npm version: 6.11.3

**Comment by SkyaTura** [comment]
Sorry reopening this issue, but the app shouldn't been able to generate working projects?
If a manual downgrade is necessary to properly work, I guess this is still an issue.

**Comment by shoichiaizawa** [comment]
Somehow, it seems to work with `2.10.0` now. I am not sure what has been fixed or what 🤔
