### ISSUE TITLE
dev: nodemon just watching server

### ISSUE THREAD

**Issue by pkej** [nuxt/create-nuxt-app#36]
During development, I noticed that nodemon is set to just watch everything in the "/server" path. I don't know why that decision was made because as soon as I start developing the generated app I prefer it to look at everything.

This might be marked as no change, but perhaps it should be documented? This is something I wouldn't have been able to catch the first time I started development with node.js and Nuxt.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c20">#c20</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @pkej 

We will work on improving this cli and the documentation related to it. Thank you for reaching out!

**Comment by MrJmpl3** [comment]
Why you need nodemon in everything?

Nuxt has Hot Reloading without Nodemon.

Nodemon is only used in server things in dev mode

**Comment by manniL** [comment]
That's right. See #147
