### ISSUE TITLE
Update Nuxt logo

### ISSUE THREAD

**Issue by manniL** [nuxt/create-nuxt-app#362]
When creating a project, the [Logo component](https://github.com/nuxt/create-nuxt-app/blob/master/template/nuxt/components/Logo.vue) still includes the old logo, while the one in the [CodeSandbox](https://github.com/nuxt/codesandbox-nuxt) is the new one already.

One could update the component :relaxed:

**Comment by Illu** [comment]
Hey, I can take care of this 🙂
