### ISSUE TITLE
Make the creation of a git repository optional

### ISSUE THREAD

**Issue by kastork** [nuxt/create-nuxt-app#366]
1. Not everyone uses git (shocking, I know)
2. Sometimes you might be creating the project in an existing repository.

**Comment by LloydTao** [comment]
Likely resolved by #596

**Comment by NozomuIkuta** [comment]
@clarkdo 

While you assign yourself to this issue, I believe this issue is already fixed by #587 and released as a part of [v3.3.0](https://github.com/nuxt/create-nuxt-app/blob/master/CHANGELOG.md#330-2020-09-17).
