### ISSUE TITLE
Fastify major version update

### ISSUE THREAD

**Issue by riteable** [nuxt/create-nuxt-app#370]
Fastify has been on version 2 for a while and it seems the generated template is compatible with it, so I think the version in the `_package.json` template can be update to the current version `^2.10.0`.

**Comment by clarkdo** [comment]
fastify has been updated to v2 by https://github.com/nuxt/create-nuxt-app/commit/952230b1227da7b05182667385eaabc4e3127281, this change will be valid in next release
