### ISSUE TITLE
Error running cli

### ISSUE THREAD

**Issue by senky** [nuxt/create-nuxt-app#371]
Hello,
after running `npx create-nuxt-app <project-name>` I get this error:
```
Trace: Error: EACCES: permission denied, open '/Users/xx/Library/Preferences/sao-nodejs/config.json.261333767'
    at Object.openSync (fs.js:451:3)
    at Function.writeFileSync [as sync] (/Users/xxx/.npm/_npx/31292/lib/node_modules/create-nuxt-app/node_modules/write-file-atomic/index.js:212:13)
    at Conf.set store [as store] (/Users/xxx/.npm/_npx/31292/lib/node_modules/create-nuxt-app/node_modules/conf/index.js:168:19)
    at Conf.set (/Users/xxx/.npm/_npx/31292/lib/node_modules/create-nuxt-app/node_modules/conf/index.js:82:14)
    at SAO.run (/Users/xxx/.npm/_npx/31292/lib/node_modules/create-nuxt-app/node_modules/sao/lib/index.js:81:13) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/xxx/Library/Preferences/sao-nodejs/config.json.261333767'
}
    at /Users/xxx/.npm/_npx/31292/lib/node_modules/create-nuxt-app/cli.js:46:17
```
I am running macOs Catalina 10.15.1 (19B88).

`ls` on `/Users/xx/Library/Preferences/sao-nodejs/` outputs:
```
config.json
```
I am not sure why it tries to open a weirdly suffixed json file. Is this anything on your side?

**Comment by clarkdo** [comment]
This file is created by package `conf`, `conf` is used by [`sao`](https://github.com/saojs/sao) for string generator info and cache answers.

If you have more questions, I suggest creating an issue in sao.js and linked this one for more accurate answers.

**Comment by yymoretime** [comment]
`rm -rf /Users/${your_user_name}/Library/Preferences/sao-nodejs`
works for me

**Comment by WhiteBetting** [comment]
> `rm -rf /Users/${your_user_name}/Library/Preferences/sao-nodejs`
> works for me

Finally, I've found this. You save me. Thanks bro

**Comment by manniL** [comment]
Closing here then ☺️ if the comment from @yymoretime resolves the issue.

**Comment by AmineKamrobotica** [comment]
hello guys i faced this error this morning unfortunately .. i solved it by :100: thank god 
steps : 
<b> 1</b>
<code> cd /tmp/node-jiti </code>

<b> 2</b>
<code> sudo rm -r * </code>

it worked so good.

**Comment by JisuPark-dev** [comment]
thank you guys, i had a same problem, and now i solve it
