### ISSUE TITLE
Koa template is not compatible with @nuxt/typescript-build

### ISSUE THREAD

**Issue by zgayjjf** [nuxt/create-nuxt-app#375]
I created a koa template just now, and add typescript support according to [https://typescript.nuxtjs.org/guide/setup.html](https://typescript.nuxtjs.org/guide/setup.html).

However, when I run `npm run dev`, `.ts` files under `store/` haven't been loaded and updated, while `.js` files worked fine.

Then I changed `npm run dev` to `nuxt`, everything works fine.

**Comment by smoonsf** [comment]
https://github.com/nuxt/typescript/issues/215

I experience simular issue. You should change your server js code to execute `await nuxt.ready();` always.

And it should be fixed to whole server js file template to execute `await nuxt.ready();` in this repo

**Comment by kevinmarrec** [comment]
Since **2.12** there's a new approach to use Nuxt.js programatically : https://nuxtjs.org/api/nuxt

If you still have an issue, please open an issue here : https://github.com/nuxt/typescript/issues
