### ISSUE TITLE
Application doesn't work

### ISSUE THREAD

**Issue by itgelo** [nuxt/create-nuxt-app#382]
I have tried creating a new project with `npx create-nuxt-app name-project` command.

`npm run dev`

I have tried with or without UI framework / server framework and I have tried changing UI framework and server framework the results are not working well.

**Comment by alxrb** [comment]
I was having a similar issue with setting up a project. Everything would work up until running `npm run dev` on the project. The client bundle wouldn't load and the site wouldn't show.

There seems to be a problem with selecting **StyleLint** in the "Choose linting tools" step of the project setup. When I didn't pick this linting option everything worked.

@itgelo Are you also selecting linting tools?

**Comment by itgelo** [comment]
@alxrb you are right, after uncheck StyleLint everything works fine.
so what's up with StyleLint?

**Comment by bm-stschneider** [comment]
the `stylelint.config.js` needs a rules property in order to work.

```
module.exports = {
  // add your custom config here
  // https://stylelint.io/user-guide/configuration
  rules: []
}
```
