### ISSUE TITLE
Add PrimeVue as an option for the UI Component Library

### ISSUE THREAD

**Issue by cagataycivici** [nuxt/create-nuxt-app#398]
We'd appreciate if PrimeVue can be added as an option for the UI Component Library;

https://www.primefaces.org/primevue/#/

**Comment by rotcl** [comment]
Haven't you tried importing as a plugin _a la carte_ [like this?](https://gist.github.com/rotcl/9bcf78dc03c9ad88c99ce72135ae1158)
Then just add in _nuxt.config.js_ this:
`plugins: [{ src: '~/plugins/primevue', ssr: false }],`
And voila, PrimeVue working on Nuxt, then you can just filter the imports and components as you need.
At least this will work as a first aproach to Nuxt + Primefaces.

**Comment by onukselcuk** [comment]
It's a shame that PrimeVue doesn't support SSR.

**Comment by zpzyyzp** [comment]
> It's a shame that PrimeVue doesn't support SSR.

https://github.com/primefaces/primevue/issues/844
Seems they fixed it?
