### ISSUE TITLE
Request to update prettier

### ISSUE THREAD

**Issue by eclectic-coding** [nuxt/create-nuxt-app#399]
I am suggesting and requesting that the installed version of Prettier to be updated to `1.19.0` minimum. With this version `vueIndentScriptAndStyle` was added to address issues related to #101 
Also, it might be helpful to add the following to `prettierrc` or at least a reference in the documentation:
`"vueIndentScriptAndStyle": true`

For reference [Prettier 1.19: Long awaited Vue option](https://prettier.io/blog/2019/11/09/1.19.0.html)

I would be glad to open a PR if you would prefer.

**Comment by clarkdo** [comment]
Resolved in v2.14.0
