### ISSUE TITLE
typescript linting issue with nuxt typescript

### ISSUE THREAD

**Issue by Rakesh-webdeveloper** [nuxt/create-nuxt-app#411]
I added the typescript to the nuxt js. But I got some linting issue, 
I created a testComponent.vue page
I copied the same data from the site
https://typescript.nuxtjs.org/cookbook/components/#template
while I run npm dev I got linitng issue
**Repo link:* https://github.com/Rakesh-webdeveloper/nuxt-app.git
pls download the and run the npm run dev. You will see the issue
<template>
  <div>Name: {{ fullName }} Message: {{ message }}</div>
</template>

<script lang="ts">
import Vue from 'vue'
interface User {
  firstName: string
  lastName: number
}
export default Vue.extend({
  name: 'TestComp',
  props: {
    user: {
      type: Object,
      required: true
    } as PropOptions<User>
  },

  data() {
    return {
      message: 'This is a message'
    }
  },

  computed: {
    fullName(): string {
      return `${this.user.firstName} ${this.user.lastName}`
    }
  }
})
</script>

Preparing project for development                                                                                                                                                                    12:54:59
ℹ Initial build may take a while                                                                                                                                                                       12:54:59
✔ Builder initialized                                                                                                                                                                                  12:54:59
✔ Nuxt files generated                                                                                                                                                                                 12:54:59

✖ Client
  Compiled with some errors in 9.03s

✔ Server
  Compiled successfully in 6.28s

ℹ Starting type checking service...                                                                                                                                                    nuxt:typescript 12:54:59
ℹ Using 1 worker with 2048MB memory limit                                                                                                                                              nuxt:typescript 12:54:59
ℹ Type checking in progress...                                                                                                                                                         nuxt:typescript 12:55:08

 ERROR  Failed to compile with 1 errors                                                                                                                                                friendly-errors 12:55:08

 ERROR  in ./pages/testPage.vue                                                                                                                                                        friendly-errors 12:55:08

Module Error (from ./node_modules/eslint-loader/dist/cjs.js):                                                                                                                          friendly-errors 12:55:08

/var/www/html/nuxt/nuxt-app-1/pages/testPage.vue
  20:6  error  Parsing error: Unexpected token, expected ","

  11 |       type: Object,
  12 |       required: true
> 13 |     } as PropOptions<User>
     |       ^
  14 |   },
  15 | 
  16 |   data () {

✖ 1 problem (1 error, 0 warnings)

 @ ./.nuxt/router.js 13:24-15:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
                                                                                                                                                                                   08
ℹ Waiting for file changes                                                                                                                                                                             12:55:08
ℹ Memory usage: 1.04 GB (RSS: 1.19 GB)                                                                                                                                                                 12:55:08

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(20,10):                                                                                                              nuxt:typescript 12:55:10
20:10 Cannot find name 'PropOptions'.
    18 |       type: Object,
    19 |       required: true
  > 20 |     } as PropOptions<User>
       |          ^
    21 |   },
    22 | 
    23 |   data () {

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(31,17):                                                                                                              nuxt:typescript 12:55:10
31:17 Object is of type 'unknown'.
    29 |   computed: {
    30 |     fullName (): string {
  > 31 |       return `${this.user.firstName} ${this.user.lastName}`
       |                 ^
    32 |     }
    33 |   }
    34 | });

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(31,40):                                                                                                              nuxt:typescript 12:55:10
31:40 Object is of type 'unknown'.
    29 |   computed: {
    30 |     fullName (): string {
  > 31 |       return `${this.user.firstName} ${this.user.lastName}`
       |                                        ^
    32 |     }
    33 |   }
    34 | });

ℹ Version: typescript 3.7.5                                                                                                                                                            nuxt:typescript 12:55:10
ℹ Time: 10999ms

**Comment by climba03003** [comment]
The Error Message already pointed the reason. As you can see the error message ```Cannot find name 'PropOptions'.```. That means you have not import the ```PropOptions``` in your code.

In line 13 of testPage.vue in your repo.
```
import Vue from 'vue'
```

In Cookbook
```
import Vue, { PropOptions } from 'vue'
```

**Comment by Rakesh-webdeveloper** [comment]
Issue is fixed

**Comment by Rakesh-webdeveloper** [comment]
Issue is fixed
