### ISSUE TITLE
TypeError Cannot read property 'firstName' of undefined

### ISSUE THREAD

**Issue by Rakesh-webdeveloper** [nuxt/create-nuxt-app#412]
}
  },

  computed: {
    fullName(): string {
      return `${this.user.firstName} ${this.user.lastName}`
    }
  }
})
</script>

I added the typescript to nuxt project
I added this script i got this issue 
https://typescript.nuxtjs.org/cookbook/components/#template

**Comment by kevinmarrec** [comment]
You were probably missing something in your `.vue` file, I don't have any issue here :

![image](https://user-images.githubusercontent.com/25272043/79052764-02ca1680-7c39-11ea-9802-812f86750f73.png)

Please open an issue on https://github.com/nuxt/typescript if you have a repository with reproduction, thanks.
