### ISSUE TITLE
project creation warning of dead libraries, please fix

### ISSUE THREAD

**Issue by bsienn** [nuxt/create-nuxt-app#417]
popper.js@1.16.1: Popper changed home, find its new releases at @popperjs/core
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3

**Comment by clarkdo** [comment]
As latest Nuxt.js is using core-js v2 by default, so this issue will be fixed after https://github.com/nuxt/nuxt.js/pull/6721 gets merged and released.
