### ISSUE TITLE
--answers <json> doesn't work

### ISSUE THREAD

**Issue by kubilaypeksen** [nuxt/create-nuxt-app#418]
i am trying any variation and the result error is any time same...

![Bildschirmfoto 2020-01-31 um 11 08 59](https://user-images.githubusercontent.com/19491631/73531759-6e169180-441b-11ea-957a-183f031edef2.png)

**Comment by clarkdo** [comment]
As `saojs` is using `JSON.parse`, so a strict json format with full prompts answers is needed, like

```bash
 create-nuxt-app  --answers '{"name": "test", ...}'
```
