### ISSUE TITLE
Use checkbox in prompts

### ISSUE THREAD

**Issue by egoist** [nuxt/create-nuxt-app#42]
https://github.com/SBoudrias/Inquirer.js#checkbox---type-checkbox

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c25">#c25</a>)</em></sub></div>

**Comment by Atinux** [comment]
👍 

We will add it for modules integration :)
