### ISSUE TITLE
Upgrade to feathers 3

### ISSUE THREAD

**Issue by Steven0811** [nuxt/create-nuxt-app#43]
This cli tool is easy for me to create a nuxt project and I love it!

but I got some question about 'why not upgrade nuxt and feathers to last version?'

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c26">#c26</a>)</em></sub></div>

**Comment by mjbates7** [comment]
I agree, would be good to see it run on the latest version or the reasons for not

**Comment by egoist** [comment]
It is using the latest version of Nuxt, PR welcome for updating feathers

**Comment by mjbates7** [comment]
I've just created a dummy project using the create nuxt-app and it doesn't list nuxt 1.4.0 as a dependency:

![image](https://user-images.githubusercontent.com/4522738/37590129-34aa86b2-2b5f-11e8-8414-c4d8da2f62e8.png)

**Comment by fuxic** [comment]
Also want to update versions

**Comment by egoist** [comment]
@mjbates7 `^` means everything greater than a particular version in the same major range.

**Comment by fuxic** [comment]
Please nuxt 1.4 / vuetify 1.0 or quasar (need author help for release) / feathers 3

**Comment by potato4d** [comment]
upgraded?
https://github.com/nuxt-community/create-nuxt-app/pull/75/files#diff-2c1b5c03cf7ce7b0571fd73c12c762e8R21

**Comment by leopiccionia** [comment]
I hacked the Express template to make it work with Feathers 3 and be `@featherjs/cli` compliant, for my personal use. Unfortunately, `feathers-vuex` is still stuck on Feathers 2.x and Vuex 2.x.

If anyone is interested, [here's the final result](https://github.com/leopiccionia/nuxt-feathers-boilerplate). If it's proved useful for more people, I can open a PR.

**Comment by gustojs** [comment]
I succesfully use Feathers 3 with Nuxt 2 and Feathers-Vuex using my Nuxt-feathers-vuex module. What issues in particular do you encounter?

**Comment by clarkdo** [comment]
featherjs 3 template has been released in create-nuxt-app 2.4.0
