### ISSUE TITLE
[Feature Request] Example json using cli option --answers

### ISSUE THREAD

**Issue by jasenmichael** [nuxt/create-nuxt-app#444]
I have tried to figure out the structure of the json used with ```npx create-nuxt-app --answers <json>```

The [cli documentation](https://github.com/nuxt/create-nuxt-app#cli-options) does not show the --answers flag as an option.

but when I run ```create-nuxt-app --help```
I get
>   "--answers \<json\>  Skip all the prompts and use the provided answers"

Would someone please show a working example usage please?
I have gotten this far.. 
```
npx create-nuxt-app --answers {"name":"new proj yo","description":"sweet-new-proj","author":"jasenmichael","pm":"npm","ui":"none","server":"none","features":{"axios","pwa","dotenv"},"linter":{},"test":"jest","mode":"spa","devTools":{"jsconfig.json"}}
```
I get an error 
```
create-nuxt-app v2.14.0
✨  Generating Nuxt.js project in description:sweet-new-proj
Trace: Error: Answers JSON could not be parsed (Unexpected token a in JSON at position 1)
```

cheers
> Nuxt changed my life...

**Comment by jasenmichael** [comment]
ok got it
```
npx create-nuxt-app --answers '{"name":"new-proj-yo","description":"sweet new proj","author":"jasenmichael","pm":"npm","ui":"none","server":"none","features":["axios","pwa","dotenv"],"linter":[],"test":"jest","mode":"spa","devTools":["jsconfig.json"]}'
```
all answers are array or string, use valid json(using all double quotes) and surround with single quotes.

**Comment by AllanOricil** [comment]
@jasenmichael  how did you find the Keys and possible values for the json we pass to --answers?

**Comment by jasenmichael** [comment]
@AllanOricil take a look round in the create-nuxt-app src code
https://github.com/nuxt/create-nuxt-app/tree/master/packages/create-nuxt-app

each option is a string or array of strings

```js
name: 'my-nuxt-project', //defaults to out folder
language:  'ts' || 'js', //only needed if using ts
features: [
  pwa,
  axios,
  content,
],
linter: [
  'eslint',
  'prettier',
  'lintStaged',
  'stylelint',
  'commitlint'
],
test: [
  'none',
  'jest',
  'ava',
  'webdriverio',
  'nightwatch'
], //defaults to none
mode: 'universal' || 'spa', //defaults to universal
target: 'server' || 'static', //defaults to server
devTools: [
  'jsconfig.json',
  'semantic-pull-requests',
  'dependabot'
], // defaults to []
ci: 'none' || 'github-actions' || 'travis-ci' || 'circleci',  // defaults to none

pm: 'yarn' || 'npm', //defaults to yarn
```

all that was found in these 2 files
https://github.com/nuxt/create-nuxt-app/blob/master/packages/create-nuxt-app/lib/prompts.js
https://github.com/nuxt/create-nuxt-app/blob/master/packages/create-nuxt-app/lib/saofile.js

**Comment by Shywim** [comment]
Got the same error using `yarn create` too, `npx` is working fine though.
