### ISSUE TITLE
Bootstrap Vue Components Not Working After NPM Run Generate 

### ISSUE THREAD

**Issue by humbertoT2** [nuxt/create-nuxt-app#445]
### Describe the bug

Building a webpage with Nuxt JS and Bootstrap Vue—Navbar dropdown functionality works as expected in dev mode but does not work when generated to static files. Clicking a dropdown item does nothing in the static files but drops down properly in development mode. 

Running npm run generate outputs expected static files with 0 errors but functionality is missing in navbar dropdown. 

### Steps to reproduce the bug

1. Clone my demo project: https://github.com/humbertoT2/bootstrap-gen-test.git

`cd /bootstrap-gen-test/
npm install
npm run generate
`
2. Open index.html in bootstrap-gen-test/dist
3. Click dropdown items in the bootstrap vue nav - they do not dropdown but html and css is loaded.

If you do not want to clone the project you can do the following. 

1. I generated this project from nuxtjs get started page with:
npx create-nuxt-app <project-name>

2. Simply choose bootstrap as your UI framework in the setup process

3. Add example dropdown nav code from bootstrap vue component docs in index.vue: 
4. npm run generate
5. open index.html in your-project-name/dist/

### Expected behavior

Navbar dropdown item functionality to work (dropdown) in static file setting

### Versions

nuxt: ^2.0.0
bootstrap-vue: ^2.0.0
bootstrap: ^4.1.3

**Environment:**

- Device:  Macbook
- Browser: Chrome

### Demo link

https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html

**Comment by clarkdo** [comment]
cc @pi0

**Comment by maxfrischknecht** [comment]
Any news on this? I have a similar problem: all bootstrap CSS classes are available while running dev mode but disappear after running `generate`.

**Comment by humbertoT2** [comment]
> Any news on this? I have a similar problem: all bootstrap CSS classes are available while running dev mode but disappear after running `generate`.

I found you need to run your generated site on a server for bootstrap vue functions to work. Simply trying to access the generated html will load a bootstrap site without bootstrap vue functionality.

**Comment by maxfrischknecht** [comment]
> > Any news on this? I have a similar problem: all bootstrap CSS classes are available while running dev mode but disappear after running `generate`.
> 
> I found you need to run your generated site on a server for bootstrap vue functions to work. Simply trying to access the generated html will load a bootstrap site without bootstrap vue functionality.

Thank's for the hint!
