### ISSUE TITLE
Run `eslint` instead `<%= pmRun %>  lint` on pre-commit hooks

### ISSUE THREAD

**Issue by munierujp** [nuxt/create-nuxt-app#485]
When `*.{js,vue}` file is going to commit, husky runs `<%= pmRun %> lint` as pre-commit hooks. (e10fe52)
It is redudant because `lint` script (`eslint --ext .js,.vue --ignore-path .gitignore .`) runs ESLint for all `.js` or `.vue` files.
I think that `"*.{js,vue}": "eslint"` works well.

Is there some reason for the current Implementation?

**Comment by clarkdo** [comment]
fixed by https://github.com/nuxt/create-nuxt-app/commit/91339542f6cb249e3ef3abe2445227a15d58480d
