### ISSUE TITLE
Adonis 4.1 support

### ISSUE THREAD

**Issue by hadihallak** [nuxt/create-nuxt-app#49]
### What problem does this feature solve?

keep the template up to date.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c31">#c31</a>)</em></sub></div>

**Comment by RaymondLC92** [comment]
Do we have any status updates regarding this?

**Comment by clarkdo** [comment]
Support for adonis 4 has been released.
