### ISSUE TITLE
Vuetify module causes error SSR

### ISSUE THREAD

**Issue by magpiedigital** [nuxt/create-nuxt-app#511]
When selecting Vuetify module in create nuxt app and deploying to google app engine, I get 500 server error.

**Comment by magpiedigital** [comment]
This was a problem with the nuxt version. create nuxt app created nuxt 2.0.0, which was somehow incompatible with the vuetify loader. But why is create nuxt app not downloading latest?

**Comment by magpiedigital** [comment]
Actually, still occurs through nuxt create app.

I was able to remove the error by downloading vuetify module separately, and updating nuxt. But if I add vuetify module in nuxt create app, and then update both veutify module and nuxt, there's still a 500 server error

**Comment by jeanpaul1304** [comment]
I have the same problem when I try to deploy my project, I'll try your solution and let you know if it works

**Comment by magpiedigital** [comment]
Let me know how it goes for you

**Comment by danielroe** [comment]
@jeanpaul1304 @magpiedigital Any chance that you need to add `vuetify` to your `dependencies` in `package.json`?

**Comment by magpiedigital** [comment]
@danielroe sorry this was a long time ago I have no idea
