### ISSUE TITLE
Nuxt servermiddleware optional chaining error

### ISSUE THREAD

**Issue by sungle3737** [nuxt/create-nuxt-app#515]
![image](https://user-images.githubusercontent.com/27716524/81273752-525dff80-908a-11ea-9e67-04b5156f6d25.png)

Does nuxt do not support optional chaining on server middleware like webpack alias feature?

**Comment by andig89** [comment]
[ServerMiddleware Example](https://codesandbox.io/s/servermiddleware-example-bt6ux?file=/nuxt.config.js)
