### ISSUE TITLE
Creating project with Eslint but without Jest causes error on @nuxtjs/eslint-config

### ISSUE THREAD

**Issue by sibbngheid** [nuxt/create-nuxt-app#521]
I'm currently using master branch on my local. Latest commit is https://github.com/nuxt/create-nuxt-app/commit/916f2887052d97272ed25c5f339a21286520e95b 

```
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):                                                                                                            friendly-errors 22:14:17
.eslintrc.js » @nuxtjs/eslint-config:
        Environment key "jest/globals" is unknown

                                                                                                                                                                           friendly-errors 22:14:17
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):                                                                                                            friendly-errors 22:14:17
Failed to load plugin 'jest' declared in '.eslintrc.js » @nuxtjs/eslint-config': Cannot find module 'json-schema'
```

**Comment by clarkdo** [comment]
@sibbngheid Are you using 'typescript' ? It seemed there is an issue https://github.com/typescript-eslint/typescript-eslint/issues/2009 , can you try to remove `yarn or npm lock` and reinstall to make sue use latest `typescript-eslint/eslint-plugin` ?

**Comment by sibbngheid** [comment]
No I'm not using Typescript. Interestingly I'm not getting this warning today when creating new app with same configuration. But the app I created last day was still broken. I tried to remove yarn.lock and run yarn, issue is gone 👌

**Comment by clarkdo** [comment]
I think it’s related to above issue I mentioned, the fix was release 20hrs ago.

Can we close this issue now?
