### ISSUE TITLE
Character entities in package.json

### ISSUE THREAD

**Issue by smhmd** [nuxt/create-nuxt-app#535]
In the CLI, entering an author name with `<email>`

![image](https://user-images.githubusercontent.com/46059092/83054235-ff081d00-a049-11ea-8dc3-f98117297ab3.png)

Adhering to package.json spec
[![image](https://user-images.githubusercontent.com/46059092/83054280-17783780-a04a-11ea-863a-a544f082ea61.png)](https://docs.npmjs.com/files/package.json)

The package.json produced by `create-nuxt-app` is

```json
"author": "smhmd &lt;contact.simohamed@gmail.com&gt;",
```
Instead of

```json
"author": "smhmd <contact.simohamed@gmail.com>",
```

**Comment by smhmd** [comment]
Not only that, but the description `Entreprise de construction et d'aménagement.` has become:
```
Entreprise de construction et d&#39;aménagement.
```

**Comment by clarkdo** [comment]
Hi @smhmd , author and description will be removed in next releasing for reducing unnecessary info during installation.

**Comment by smhmd** [comment]
If that's the case, I'll close the issue. I think they're useful enough. Is there an issue related to that?

**Comment by clarkdo** [comment]
This is the pr https://github.com/nuxt/create-nuxt-app/pull/466
