### ISSUE TITLE
"Then we’ll order Node.js to listen to the server configured". Confused

### ISSUE THREAD

**Issue by DogsAreTheShit** [nuxt/create-nuxt-app#537]
I'm currently trying to follow along with this article https://medium.com/@stfalconcom/chat-app-creation-using-vue-js-nuxt-js-node-js-socket-io-vue-socket-io-vuetify-js-technologies-5f15f0781476
and am a little confused. I'm lost as to which js file im adding new code to for this step "Then we’ll order Node.js to listen to the server configured". Am I editing those lines of code into the index.js file in the servers folder? or is this a different js file. 

Appreicate any help

![Screen Shot 2020-05-29 at 2 48 19 PM](https://user-images.githubusercontent.com/65428292/83294672-a5bffb00-a1bb-11ea-8187-9ca90fa24e98.png)

**Comment by clarkdo** [comment]
From the artical in your comment, I think the repo is https://github.com/psborul/nuxt-chat-app , so the server file is https://github.com/psborul/nuxt-chat-app/blob/master/server/index.js
