### ISSUE TITLE
@nuxtjs/tailwindcss v1 instead of v2

### ISSUE THREAD

**Issue by web2033** [nuxt/create-nuxt-app#548]
I see here v2 in [source](https://github.com/nuxt/create-nuxt-app/blob/master/packages/cna-template/template/frameworks/tailwind/package.json) but I get v1 when choosing Tailwind CSS:
```
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^1.0.0"
  }
```
It seems not the same as omitting Tailwind and installing the module
https://github.com/nuxt-community/tailwindcss-module
which has different purgecss options than v1.

**Comment by MrJmpl3** [comment]
I get v2 version. 😀

**Comment by tobiasmuehl** [comment]
Also got 2.0 `"@nuxtjs/tailwindcss": "^2.0.0",`

**Comment by manniL** [comment]
> I see here v2 in [source](https://github.com/nuxt/create-nuxt-app/blob/master/packages/cna-template/template/frameworks/tailwind/package.json?rgh-link-date=2020-06-11T17%3A39%3A27Z) but I get v1 when choosing Tailwind CSS:
> 
> ```
>   "devDependencies": {
>     "@nuxtjs/tailwindcss": "^1.0.0"
>   }
> ```
> 
> It seems not the same as omitting Tailwind and installing the module
> [nuxt-community/tailwindcss-module](https://github.com/nuxt-community/tailwindcss-module)
> which has different purgecss options than v1.

Please ensure that you use the latest version of `create-nuxt-app`. We are using `v2` for quite a while 😋
