### ISSUE TITLE
CNA should fail if the target directory is not empty

### ISSUE THREAD

**Issue by jamesgeorge007** [nuxt/create-nuxt-app#556]
Say, we have got a directory `my-app` in the current path. Firing in `create-nuxt-app my-app` goes ahead generating the project files within that directory.

**Comment by erik-ekberg-sg** [comment]
There should be a way to bypass this through a `--force`-like argument. I like the safeguard of not accidentally delete / overwriting users files by default, however, there should be a way to overwrite those warning.

I am trying to create a new Nuxt application inside a Docker container so the directory already contains the `Dockerfile` preventing the Nuxt application from generating.
