### ISSUE TITLE
I create projects ，cannot select Server framework

### ISSUE THREAD

**Issue by 1161740194** [nuxt/create-nuxt-app#559]
I want to use Express，How to choose

**Comment by chenjinchao1997** [comment]
feat(templates): deprecate server templates #501
[https://github.com/nuxt/create-nuxt-app/pull/501](url)
look like they deprecate server templates

**Comment by manniL** [comment]
as @chenjinchao1997 mentioned, server templates are deprecated. 

Either use `serverMiddleware` or a standalone service instead 😄 

PS: I've written about [my take on using an API with Nuxt](https://blog.lichter.io/posts/nuxt-with-an-api/) some time ago.

**Comment by robbylucia** [comment]
Various reasons aside, they were easy.
For those who wish to go back to when it was easy, use the last working version with:
`npx create-nuxt-app@2.15.0`

**Comment by wizardpisces** [comment]
Where can we see the so called various reasons about removing server template? I could not see the necessity of this change for now... From my perspective, it's just another feature which only increasing the mental burden and nothing more,( and another round of issues )

**Comment by pi0** [comment]
Hi. This is dup of #563. @robbylucia @wizardpisces please continue following up #563 instead of commenting in several places!
