### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by screetBloom** [nuxt/create-nuxt-app#561]
Hi there，some confusion：
- Why not use [Vue CLI for creating projects](https://cli.vuejs.org/guide/creating-a-project.html) 
- and why we must recreate  「create-nuxt-app」

**Comment by pi0** [comment]
Hi @screetBloom. Actually both `vue-cli` and nuxt are in some ways similar frameworks but have totally different project structures and generation systems. This cli is to create a nuxt project structure.

**Comment by screetBloom** [comment]
> Hi @screetBloom. Actually both `vue-cli` and nuxt are in some ways similar frameworks but have totally different project structures and generation systems. This cli is to create a nuxt project structure.

If that's the only purpose, why not write a [Vue Cli plugin](https://cli.vuejs.org/zh/dev-guide/plugin-dev.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E6%A8%A1%E6%9D%BF)?

**Comment by screetBloom** [comment]
> > Hi @screetBloom. Actually both `vue-cli` and nuxt are in some ways similar frameworks but have totally different project structures and generation systems. This cli is to create a nuxt project structure.
> 
> If that's the only purpose, why not write a [Vue Cli plugin](https://cli.vuejs.org/dev-guide/plugin-dev.html#generator)?
> I'd appreciate it if some one tell me why

@pi0  Do you have any other ideas you'd like to share?

**Comment by pi0** [comment]
@screetBloom Kindly this is not a matter to discuss because of different requirements and at a point of time, CNA will be merged with nuxt cli. Mixing two frameworks is not a good idea and we are already using awesome [sao](https://github.com/saojs/sao) tool so we are also not reinventing the wheel :)

**Comment by egoist** [comment]
short answer: because CNA was created way before Vue CLI 3
