### ISSUE TITLE
Creating a new app with Typescript results in the "dev" script using nuxt instead of nuxt-ts

### ISSUE THREAD

**Issue by ccw-morris** [nuxt/create-nuxt-app#565]
This week I created a new nuxt project with TypeScript support, and yesterday I added serverMiddleware - which failed due to a syntax error. The problem was that the serverMiddleware wasn't being compiled from TypeScript into JavaScript.

This issue was caused by the "dev" script in package.json being "nuxt" rather than "next-ts". Changing it resolved the issue locally.

https://github.com/nuxt/create-nuxt-app/blob/master/packages/cna-template/template/nuxt/package.js#L83
The above line transforms the package.json when Typescript support is enabled. Note that the pattern is /^nuxt / - which will only match the script if there is a space after the word nuxt, and therefore doesn't match the script "nuxt".

**Comment by DavidDomkar** [comment]
Just spent an hour trying to find why importing in typescript script tags was not working. It was because of this. It seems that the regex pattern has been already fixed. Hope new release will come out soon.

**Comment by MrJmpl3** [comment]
I think that was fixed to the next release: https://github.com/nuxt/create-nuxt-app/pull/568
