### ISSUE TITLE
How can I integrate socket.io with nuxt-app?

### ISSUE THREAD

**Issue by masked-rider** [nuxt/create-nuxt-app#571]
Or how and where can I get the http(s).Server object?

**Comment by EmmyMay** [comment]
> Or how and where can I get the http(s).Server object?

I guess you'd have to initialize nuxt with either Express or Koa?

**Comment by EmmyMay** [comment]
https://medium.com/javascript-in-plain-english/introduction-to-nuxt-socket-io-b78c5322d389

I found this article on the topic. Apparently, there is a module. I love the dev community.

**Comment by masked-rider** [comment]
Hi, EmmyMay! Thanks. It's so nice of you to give me the information. I could fix the problem!
