### ISSUE TITLE
How did the latest version create a project without the node framework option

### ISSUE THREAD

**Issue by Edison-Ma** [nuxt/create-nuxt-app#575]
I remember only supporting it before

**Comment by aldarund** [comment]
Its not recommended to run backend with frontend same time. https://github.com/nuxt/create-nuxt-app/pull/501
Please use separate projects and if  you need it and u understand what u are doing use serverMiddleware

**Comment by aldarund** [comment]
Its not recommended to run backend with frontend same time. https://github.com/nuxt/create-nuxt-app/pull/501
Please use separate projects and if  you need it and u understand what u are doing use serverMiddleware
