### ISSUE TITLE
Allow for creating app inside current directory like Vue CLI

### ISSUE THREAD

**Issue by lloydjatkinson** [nuxt/create-nuxt-app#582]
Vue CLI allows the user to create a new app inside the current directory, and it will name the app the same as the directory:

```bash
vue create .
```

The use case for this is that it's really common to first create a repository (e.g. on GitHub), clone it, and then create the new app.

Right now to do the same with `create-nuxt-app` the user has to run (eg the repo name is my-website.com):

```bash
npx create-nuxt-app my-website.com
```

This means you end up with `my-website.com\my-website.com` and then you need to basically move the contents up one directory to be in the root.

**Comment by TheMangoTrain** [comment]
I agree with the use case, 

For reference, you can just move all the files from the newly created sub-folder, into the root of the repo.

**Comment by fu9da** [comment]
In v3.4.0, you can specify the current directory and execute.
But the specified directory must be empty.

```
Can't create . because there's already a non-empty directory . existing in path.
```

As a result, it seems that there are many cases where it is used as described above.

As mentioned in https://github.com/nuxt/create-nuxt-app/issues/556#issuecomment-674555335,
I would be happy if there is a way to byapass this, such as with `--force`.

**Comment by lloydjatkinson** [comment]
You can, but if there is a hidden .git directory from the previously mentioned “creating it on GitHub first” it won’t work.

**Comment by lloydjatkinson** [comment]
This is still an issue that would make life much easier if fixed

**Comment by blackeuler** [comment]
What would need to be done to make this happen?

**Comment by matgnt** [comment]
it's also a problem when working with Visual Studio Code and DevContainers [1]. Then you always have a hidden ".devcontainer" directory there and you always have to create the nuxt app in a sub-directory.

[1] https://code.visualstudio.com/docs/remote/containers

**Comment by utamori** [comment]
sveltekit also allows you to create a project for the directory where the files reside
Hopefully this behavior will be possible in Nuxt3 🙏

**Comment by clarkdo** [comment]
https://github.com/nuxt/create-nuxt-app/pull/799 (--overwrite-dir) has been merged and released
