### ISSUE TITLE
GIt Bash Options not matching crusor

### ISSUE THREAD

**Issue by obtusedev** [nuxt/create-nuxt-app#588]
Using `npx create-nuxt-app my-app` on Git Bash(latest version) causes the options to not match up. When selecting between JavaScript or TypeScript, selecting JavaScript actually selects TypeScript and the same with choosing betwen Yarn and NPM.
The crusor for selecting any of the options are not matching. Placing crusor over none for UI makes it select ANT design instead.

**Comment by azrikahar** [comment]
Are you still having this issue? I tried using Git Bash on my machine and I don't seem to have this issue on my end.

Enviroment info:
- Windows 10 version 2004
- Git version 2.28.0.windows.1
- create-nuxt-app v3.2.0 (from screenshot)

Screenshot: (pixelated laptop name, not a bug)
![cmd_649YEmBo4A](https://user-images.githubusercontent.com/42867097/91982573-0895d500-ed5d-11ea-9bb7-e3c3d9d5c50f.png)

**Comment by obtusedev** [comment]
Still having this issue. My Git Bash font size is 12pt and font is Fira Code. Here is a video demostrating the bug. [Video](https://streamable.com/p9unod)
