### ISSUE TITLE
Potential Malicious dependency trying to read .steampath

### ISSUE THREAD

**Issue by chris-aeviator** [nuxt/create-nuxt-app#591]
When using `create-nuxt-app` and chosing `pwa, bootstrap, javascript, ssr`, I can see a  failed access to the (intentionally broken) Steam (https://store.steampowered.com/)  Simlink ` ERROR  ENOENT: no such file or directory, stat '/home/korny/.steampath'           12:35:35` (!!!)

It looks like some npm module is trying to access steam credentials

**Comment by pi0** [comment]
Hi @chris-aeviator is it happening right after project creation?

**Comment by pi0** [comment]
Update: Using latest version + yarn + bootstra/pwa/eslint/axios on linux i couldn't trace any fs access to `$HOME/.steampath`. It might be something critical but at least not reproducible. So we need more information. Also feel free directing me in discord to have a video call.

**Comment by pi0** [comment]
Related:
- https://github.com/facebook/create-react-app/issues/9156
- https://stackoverflow.com/questions/62488286/linux-mystery-how-does-running-a-node-module-gatsby-result-in-an-steampath-e

**Comment by chris-aeviator** [comment]
@pi0 I'm trying to pinpoint it down. I cannot reproduce with a plain install, but as soon as copying over some page & component templates, without installing more NPM dependencies I will get it, I will try step by step. The call stack of this is endless, the access is coming over `fs.stat` , called by processNextTick. Will post an update as soon as I find out more

**Comment by chris-aeviator** [comment]
reading through your links it might be exactly that, I copy over components which might have missing dependencies, nodejs scanning my home folder for a `node_modules` folrder (which does not exist) and running over the `.steampath` which is an (intentionally) broken symlink and complaining

**Comment by WiseTap** [comment]
I had a similar problem, was because that I was importing the _nuxt.config_ file:
`require("../nuxt.config")`
