### ISSUE TITLE
[Typescript] Created Application fails to compile

### ISSUE THREAD

**Issue by lambda0xff** [nuxt/create-nuxt-app#601]
Steps to reproduce:

1. yarn create-nuxt-app test
2. Typescript
3. Yarn
4. Tailwind CSS
5. None
6. None
7. Jest
8. Universal
9. Static
10. jsconfig.json

cd test / yarn dev -> 

ERROR Failed to compile with 1 error
This relative module was not found
* ./index.vue?vue&type=script&lang=ts& in ./pages/index.vue

version: create-nuxt-app/3.2.0 darwin-x64 node-v14.5.0

**Comment by jfx** [comment]
Hello,

I have this issue with almost the same installation choices with node version 12.
An error is displayed on the web page: 
`Module not found: Error: Can't resolve 'ts-loader'`

I added in devDependencies of package.json
`"ts-loader": "^8.0.3",`
And it works

**Comment by lambda0xff** [comment]
@jfx Yep, that seems to fix it. Merci !

**Comment by kewp** [comment]
Hello. I had exactly the same issue with a clean app using TypeScript. The fix above worked, but I think a lot of people won't find this fix!
