### ISSUE TITLE
missing modules when creating ts demo

### ISSUE THREAD

**Issue by aquariuslt** [nuxt/create-nuxt-app#602]
## Re-produce Settings
- Programing Language: TypeScript
- Package manager: Yarn
- UI Framework: Ant Design Vue
- Nuxt.js modules: Axios
- Linting tools: ESLint, Prettier, Lint staged files
- Testing framework: Jest
- Rendering mode: Universal (SSR/SSG)
- Server (Node.js hosting)
- Development tools: semantic PRs

## Error

When executing `yarn dev` 

and open browser with dynamic listen url

UI Throws `Cannot find module './index.vue?vue&type=script&lang=ts&'`

![image](https://user-images.githubusercontent.com/6554061/92372353-647ea600-f12f-11ea-90f2-cf9970d4433f.png)

**Comment by manniL** [comment]
Resolved in https://github.com/nuxt/create-nuxt-app/pull/599
