### ISSUE TITLE
Dockerizing a Nuxt.js web app

### ISSUE THREAD

**Issue by MirlanJA** [nuxt/create-nuxt-app#614]
Hi everybody!

I need your opinions and comments.

I did dockerization of `creat-nuxt-app`, that is, now you can start the process of installing a template on docker with one command `docker-compose up`.

https://github.com/MirlanJA/nuxtdocker

All questions when running the `init nuxt-app` command can be configured in the `env` file.

I will write a complete guide soon.

**Comment by raminjafary** [comment]
What are you going to do with a dockerized template? I mean what next?
