### ISSUE TITLE
Create nuxt project use  create-nuxt-app(3.2.0 select typescript) runing error

### ISSUE THREAD

**Issue by siegaii** [nuxt/create-nuxt-app#616]
I build nuxt project use create-nuxt-app(3.2.0 select typescript), runing error.

The cli install @nuxt/typescript-runtime version 1.0.0 in dependencies, I think it's should install version 2.0.0 in devDependencies

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/create-nuxt-app/issues/602
Fixed in https://github.com/nuxt/create-nuxt-app/pull/599

Release pending (cc @pi0)
