### ISSUE TITLE
Navigation link errors in nuxt.config.js

### ISSUE THREAD

**Issue by eclectic-coding** [nuxt/create-nuxt-app#662]
This is an observation. 

In the `nuxt.config.js` file, generated from a new app installation, depending on the editor in which they are view, the hyperlinks *can* be broken links. 

**Reproduce**
- In VSCODE or WEBSTORM, open the `nuxt.config.js` file, hover over the following link, and when you use the appropriate keyboard shortcut for the editor, and click the link, the URL opens properly:
```json
// Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [],
```
- However, if you use a CLI editor (i.e. Vim, Nano, or even less), hover over the link and click, the final `)` is added to the URL and results in a 404 error. 

**Suggested Fix**
To enhance the user experience across all platforms and editors, there are two possible fixes to correct this problem:
- Add a space around the link:  
```json
// Plugins to run before rendering page ( https://go.nuxtjs.dev/config-plugins )
  plugins: [],
```
- Or change the text line to a `:` and remove the `( ... )`
```json
// Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],
```
Both of these suggested fixes with correct the errors

I will be glad to open a PR. 

Thank you for such a great product. 
Chuck Smith

**Comment by eclectic-coding** [comment]
I will submit a PR later today.

**Comment by NozomuIkuta** [comment]
@clarkdo 

FYI: 
I believe this issue can be closed because the PR has been already merged.
The PR was not linked to this issue (possibly because of lack of "Resolves" phrase?).
