### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by bearkfear** [nuxt/create-nuxt-app#665]
When create a project and select Typescript And Axios, the axios types is not been included in tsconfig!

**Comment by giuseppecampanelli** [comment]
@bearkfear Are you sure you selected Axios by hitting spacebar on the option when running create-nuxt-app?
Refer to https://i.imgur.com/poRtKgd.png

I tested with the latest version of create-nuxt-app (3.5.2) and see @nuxtjs/axios present in types in tsconfig.js.
Refer to https://i.imgur.com/8Sc0gyQ.png
