### ISSUE TITLE
Can I add something from the install wizard later

### ISSUE THREAD

**Issue by kevincam3** [nuxt/create-nuxt-app#673]
After setting up a project originally using Prettier and not ESLint, I decided I now what to add ESLint as well. Is there a way I can do this so that it configures Prettier & ESLint properly or do I have to do it all manually now?

**Comment by pi0** [comment]
Hi @kevincam3. Short answer is no. CNA is a scaffold tool. But longer answer is that new nuxt CLI will have this functionality to do atomic changes.

**Comment by kevincam3** [comment]
@pi0,

Thanks for the quick response. Looking forward to it.
