### ISSUE TITLE
Add Vant an UI framework Option

### ISSUE THREAD

**Issue by chanjsq** [nuxt/create-nuxt-app#675]
As [Vant](https://youzan.github.io/vant) is a popular UI component library.

Can we add it as an option?

Thank you! ❤️

**Comment by themilanfan** [comment]
Started PR #708

**Comment by themilanfan** [comment]
Created PR for this #710

**Comment by NozomuIkuta** [comment]
@ChangJoo-Park

#719 is already released as [v3.6.0](https://github.com/nuxt/create-nuxt-app/releases/tag/v3.6.0), and fixed in [v3.7.0](https://github.com/nuxt/create-nuxt-app/releases/tag/v3.7.0).
You might want to try v3.7.0 and close this issue.

**Comment by chanjsq** [comment]
@NozomuIkuta Thank you!!! ❤️
