### ISSUE TITLE
Gitignore in assets folder?

### ISSUE THREAD

**Issue by christophstockinger** [nuxt/create-nuxt-app#678]
I had the problem several times now that my build pipelines failed because there was a .gitignore file in the assets folder.

This file ignored all other files in the assets folder.
As a result, the required assets were not committed with and thus were not available in the build process.

After a long search I found the gitignore file and deleted it. Then the pipeline ran through flawlessly.

But unfortunately it is a mystery to me why this file is created. I also can't find a file in the template that solves the mystery.

Does anyone of you have an explanation?

**Comment by danielroe** [comment]
For the benefit of posterity: see https://github.com/nuxt/nuxt.js/issues/8512
