### ISSUE TITLE
yarn create nuxt-app using node v15.4.0

### ISSUE THREAD

**Issue by lightmyfire17** [nuxt/create-nuxt-app#679]
Facing error while running `yarn create nuxt-app`:

```
create-strapi-app@3.2.3: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <13". Got "15.4.0"
error Found incompatible module.
```

So, I think, the migration to new strapi is needed.

_System: Windows 10
Node: v15.4.0
Yarn: 1.19.1_

**Comment by clarkdo** [comment]
From the console, the error is from create-strapi-app, I'm not quite clear what is related to create-nuxt-app ?

**Comment by lightmyfire17** [comment]
![image](https://user-images.githubusercontent.com/19778699/103906370-e0562280-5110-11eb-998f-f7112919f6f3.png)

Just copy&paste from the docs `yarn create nuxt-app <my-project>`

**Comment by clarkdo** [comment]
I don't think we depends on anything from create-strapi-app, I suppose it's related to your env like yarn link, alias or global packages. Can you please run `yarn create --verbose nuxt-app` and find where create-strapi-app is from in verbose log ?

**Comment by lightmyfire17** [comment]
![image](https://user-images.githubusercontent.com/19778699/103909522-ddf5c780-5114-11eb-9617-de89b1213ff2.png)

**Comment by lightmyfire17** [comment]
BTW with npx and yarn combo it works totally fine.

**Comment by clarkdo** [comment]
Can you paste prior logs around line `Performing "GET" request to "https://registry.yarnpkg.com/create-strapi-app"` ?

**Comment by clarkdo** [comment]
Have you tried uninstalling create-nuxt-app globally and run yarn create nuxt-app again ?

```js
yarn global remove create-nuxt-app
npm uninstall -g create-nuxt-app
``

**Comment by lightmyfire17** [comment]
> Can you paste prior logs around line `Performing "GET" request to "https://registry.yarnpkg.com/create-strapi-app"` ?

Funniest thing is that it's there's no such line in logs...



> Have you tried uninstalling create-nuxt-app globally and run yarn create nuxt-app again ?
> 
> ```shell
> yarn global remove create-nuxt-app
> npm uninstall -g create-nuxt-app
> ```

Doesn't help

**Comment by clarkdo** [comment]
I've no idea why `nuxt-app` is pointing to `strapi-app` in your env, are you using `create-strapi-app` locally ? Maybe you can try to remove it as well.

**Comment by lightmyfire17** [comment]
If it's 100% my local problem feel free to close the issue, thanks for the help I'll fix it.

**Comment by corneelonline** [comment]
I experienced the exact same problem. The answer of @clarkdo led me to trying this:
```
yarn global remove create-nuxt-app
yarn global remove create-strapi-app
```
Then when I tried running `yarn create nuxt-app <my-app>` again it installed `create-nuxt-app` and started the nuxt installation procedure.

**Comment by nagman** [comment]
I encountered the same issue. By removing globally the `create-strapi-app` and the `strapi` packages, I've been able to run `yarn create nuxt-app` with the lts version of node (16).


> I don't think we depends on anything from create-strapi-app, I suppose it's related to your env like yarn link, alias or global packages.

Looks like so. I may have installed strapi with an older version of node last year, and yarn seems to have trouble with resolving links.
