### ISSUE TITLE
Babel is not working

### ISSUE THREAD

**Issue by chaos-zhu** [nuxt/create-nuxt-app#680]
`System: Windows 10`
`Node: v14.15.3`
`Yarn: 1.22.5`

#### nuxt.config.js 
```js
    babel: {
      presets({ isServer }) {
        const targets = isServer ? { node: 'current' } : { ie: 9}
        return [
          [ require.resolve('@nuxt/babel-preset-app'), { targets } ]
        ]
      }
    }
```

#### index.vue

```js
mounted() {
    console.log(Promise.allSettled)
}
```

#### IE9~IE11
return `undefined`

**Comment by clarkdo** [comment]
@chaos-zhu I think this may be related to core-js version, v2 doesn't support Promise.allSettled, can you double confirm if you're using core-js 3 ?

**Comment by chaos-zhu** [comment]
> @chaos-zhu I think this may be related to core-js version, v2 doesn't support Promise.allSettled, can you double confirm if you're using core-js 3 ?

I install corejs module，but it still not working in IE.
```js
build {
  babel: {
    presets({ isServer }) {
      if(isServer) return [[ require.resolve('@nuxt/babel-preset-app'),  {targets: { node: 'current' }} ]]
      return  [ [ '@babel/preset-env', { "useBuiltIns": "usage", "corejs": "3", "targets": "ie >= 9" } ] ]
    }
  }
}
```

**Comment by clarkdo** [comment]
This issue will be fixed by https://github.com/nuxt/nuxt.js/pull/8545.

As a quick fix, you can set `corejs.proposals` of `@nuxt/babel-preset-app`


```js
corejs: { version: 3, proposals: true }
```
