### ISSUE TITLE
line:style on MacOS has side effect due to terminal glob pattern picking it

### ISSUE THREAD

**Issue by fuxingloh** [nuxt/create-nuxt-app#681]
https://github.com/nuxt/create-nuxt-app/blob/7bd65f3837be8291ef6c2d20ec55d38bd42cb94f/packages/cna-template/template/nuxt/package.json#L8

### On MacOS
Running it directly works: `stylelint **/*.{vue,css} --ignore-path .gitignore`.
Running it via `npm run lint:style` will fail and errors will be silenced as the path is not picked up due to built-in glob pattern.
In [stylelint docs](https://stylelint.io/user-guide/get-started), `npx stylelint "**/*.css"`  was used.

Hence, adding `\"**/*.{vue,css}\"` quotation fixes it for me, but I am unsure of other OS side effect.

```json
    "lint:style": "stylelint \"**/*.{vue,css}\" --ignore-path .gitignore"
```

**Comment by clarkdo** [comment]
Thanks for the report, I think adding quotes is a good fix, I'll open a pr.
