### ISSUE TITLE
@nuxtjs/axios not in types tsconfig.json

### ISSUE THREAD

**Issue by dawidstefaniak** [nuxt/create-nuxt-app#690]
Hi,
After using create-nuxt-app, the Axios has been bootstrapped.

If you are using TypeScript, you need to have ` "@nuxtjs/axios"` defined in `types` array in `compilerOptions` object of the `tsconfig.json`. If you don't do it, the compiler shows you error, that "$axios is not defined on type Context".

I propose adding ` "@nuxtjs/axios"` to types by default to not get this error.

**Comment by danielroe** [comment]
Agreed. Following this pattern would be good: https://github.com/nuxt/create-nuxt-app/pull/688

**Comment by clarkdo** [comment]
v3.5.0 has been published

**Comment by danielroe** [comment]
Is this implemented?

**Comment by clarkdo** [comment]
Sorry, I thought it's @nuxt/content
