### ISSUE TITLE
comment URL outdated

### ISSUE THREAD

**Issue by Cygra** [nuxt/create-nuxt-app#706]
https://github.com/nuxt/create-nuxt-app/blob/5000f113ca4790fbbf97d673cb0af0dcd0a9e91a/packages/create-nuxt-app/lib/cli.js#L47

url's now here: https://sao.vercel.app/api.html#standalone-cli

**Comment by themilanfan** [comment]
Created PR #707

**Comment by giuseppecampanelli** [comment]
This could probably be closed now since the PR was merged.
