### ISSUE TITLE
how to debug with create-nuxt-app@3.x app?

### ISSUE THREAD

**Issue by bi-kai** [nuxt/create-nuxt-app#716]
when i am using with create-nuxt-app@2.x, there has `nodemon` in dev command, I can debug front-end code and back-end code at the same time.

but:
"scripts": {
    "dev": "nuxt",
}
I cannot see origin source code in chrome source panel.
![image](https://user-images.githubusercontent.com/15070379/107854076-80137880-6e54-11eb-8c93-133870fc584a.png)

**Comment by clarkdo** [comment]
I think you can use `node --inspect ./node_modules/.bin/nuxt dev`, then use [Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) or other IDE debug tools.

**Comment by bi-kai** [comment]
@clarkdo thx, this is helpful for me.
