### ISSUE TITLE
remove `nuxt-ts` as no longer required

### ISSUE THREAD

**Issue by danielroe** [nuxt/create-nuxt-app#719]

**Comment by clarkdo** [comment]
`nuxt-ts` is from `@nuxt/typescript-runtime` not previous `nuxt-ts`, so  I think it should be fine ?

**Comment by danielroe** [comment]
With `jiti`, we can define `serverMiddleware` and `nuxt.config` in Typescript, so we don't require `nuxt-ts` installed by default in new TS projects.

**Comment by clarkdo** [comment]
What about internal nuxt module like `~/modules/socketClient` ?
