### ISSUE TITLE
Remove the Vuesax UI Framework

### ISSUE THREAD

**Issue by stuible** [nuxt/create-nuxt-app#779]
Vuesax appears to be dead and is definitely not being maintained.  I unfortunately made the mistake of using it as the base of a project without doing proper due diligence because it was included as a Nuxt UI Framework.  I would highly recommend it be removed to avoid people from making a similar mistake.  It is incomplete, missing many features, and contains bugs including accessibility issues that will not be fixed.  Many people have tried to reach out to the creator without success: https://github.com/lusaxweb/vuesax-next/issues

Thank you for all your work on Nuxt.js, it's an amazing project!

Edit:
Here is a more specific issue with many people chiming in on the issues surrounding the project: https://github.com/lusaxweb/vuesax-next/issues/129

If you would like me to create a pull request that removes this project, I'm more than happy to do it.

**Comment by clarkdo** [comment]
Thanks for the reporting, we’ll look into this
