### ISSUE TITLE
PurgeCSS

### ISSUE THREAD

**Issue by jericopulvera** [nuxt/create-nuxt-app#78]
### What problem does this feature solve?

Saves time setting up purgecss on new project.

### What does the proposed changes look like?

Should have an option to add purgecss

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c55">#c55</a>)</em></sub></div>

**Comment by aldarund** [comment]
The thing is that it dont play well with some frameworks. For example with vuetify

**Comment by manniL** [comment]
It got easier with https://github.com/Developmint/nuxt-purgecss
But it's hard to "integrate it by default" due to the reason @aldarund explained

**Comment by jericopulvera** [comment]
How about having this additional option only if it works in the UI framework chosen?

**Comment by carlos-avila** [comment]
Created #430 to start addressing this issue.
