### ISSUE TITLE
Babel "loose" option error spamming in console on fresh project

### ISSUE THREAD

**Issue by utshomax** [nuxt/create-nuxt-app#782]
**The Issue:** 
https://github.com/nuxt/nuxt.js/issues/9224#issue-872747599

_Solution (Temp):_

> With yarn, please pin your babel deps manually in your `package.json`, then use `yarn install` again:
> 
> ```json
> "resolutions": {
>   "@babel/core": "7.13.15",
>   "@babel/preset-env": "7.13.15"
> }
> ```
> 
> With npm, add these as dev deps (with the same versions).

_Originally posted by @manniL in https://github.com/nuxt/nuxt.js/issues/9224#issuecomment-830237126_

**The Question:** 

Shouldn't the create-nuxt-app add those devDependencies by default while creating the project?

**Comment by aldy505** [comment]
>Shouldn't the create-nuxt-app add those devDependencies by default while creating the project?

Yes, it is. But nuxt is using ^ (caret) on their @babel/core and @babel/preset-env version. See [here](https://stackoverflow.com/a/22345808) for more info about that. Then, two days ago a minor version was released on @babel/core and @babel/preset-env which causes the bug.

**Comment by utshomax** [comment]
Closing this issue since this [PR](https://github.com/nuxt/nuxt.js/pull/9226#issue-628407473) of  nuxt seems solves the problem.
