### ISSUE TITLE
Babel Config: preset loose: true value will not be used on npm run dev

### ISSUE THREAD

**Issue by SwapnilSoni1999** [nuxt/create-nuxt-app#783]
create-nuxt-app version: 3.6.0
node version: 16.0.0
os: archlinux x86_64

I've created a nuxt app using `create-nuxt-app` and after running `npm run dev` it shows the following warning. The app works fine but this error gets spammed in the console.

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
```

**Comment by danielroe** [comment]
Root issue: https://github.com/nuxt/nuxt.js/issues/9224

**Comment by SwapnilSoni1999** [comment]
> Root issue: [nuxt/nuxt.js#9224](https://github.com/nuxt/nuxt.js/issues/9224)

alright so closing this one
