### ISSUE TITLE
Warning: .babelrc removed

### ISSUE THREAD

**Issue by NguyenThanh1995** [nuxt/create-nuxt-app#786]
Hi,

It seems that in the recent update of the nuxt template the .babelrc file was removed and a warning was generated.
Please re-add this file

![image](https://user-images.githubusercontent.com/45375496/117536900-eceb7880-b027-11eb-98d5-3b46826d9546.png)

**Comment by clarkdo** [comment]
This has been fixed by https://github.com/nuxt/nuxt.js/pull/9232
