### ISSUE TITLE
ESOCKETTIMEDOUT when yarn create nuxt-app

### ISSUE THREAD

**Issue by morandalex** [nuxt/create-nuxt-app#788]
hello! 
I have problems creating the nuxt-app

Here the log

    $ yarn create nuxt-app ctc --network-timeout 100000
    yarn create v1.22.10
    [1/4] Resolving packages...
    warning create-nuxt-app > sao > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    warning create-nuxt-app > sao > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    [2/4] Fetching packages...
    [#########################################################################################################################################################################################################-] 317/318 
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT".
    info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\amorandi\\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

.

    Arguments: 
      C:\Program Files\nodejs\node.exe C:\Users\amorandi\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js create nuxt-app ctc --network-timeout 100000
    
    PATH: 
      C:\Users\amorandi\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\amorandi\bin;C:\Program Files (x86)\IBM\WebSphere MQ\Java\lib;C:\Python39\Scripts;C:\Python39;C:\oracle\product\10.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files (x86)\Google\Google Apps Sync;C:\Program Files (x86)\Google\Google Apps Migration;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files (x86)\IBM\WebSphere MQ\bin64;C:\Program Files (x86)\IBM\WebSphere MQ\bin;C:\Program Files (x86)\IBM\WebSphere MQ\tools\c\samples\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\amorandi\AppData\Local\Microsoft\WindowsApps;C:\Users\amorandi\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
    
    Yarn version: 
      1.22.10
    
    Node version: 
      14.16.0
    
    Platform: 
      win32 x64
    
    Trace: 
      Error: https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT
          at ClientRequest.<anonymous> (C:\Users\amorandi\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141289:19)
          at Object.onceWrapper (events.js:421:28)
          at ClientRequest.emit (events.js:315:20)
          at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
          at Object.onceWrapper (events.js:421:28)
          at TLSSocket.emit (events.js:327:22)
          at TLSSocket.Socket._onTimeout (net.js:483:8)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)
    
    npm manifest: 
      No manifest
    
    yarn manifest: 
      No manifest
    
    Lockfile: 
      No lockfile

**Comment by danielroe** [comment]
@morandalex It looks like you might have had a network issue when yarn was downloading `rxjs`. Does it still happen if you try again?
