### ISSUE TITLE
Lost folders when create nuxt-app

### ISSUE THREAD

**Issue by matamune94** [nuxt/create-nuxt-app#808]
Folders: layouts, middleware, plugins,  assets
Has it been removed? or error?

**Comment by rifftrader** [comment]
Sae here.

**Comment by BrainAxe** [comment]
same here.
@rifftrader, your solution didn't work.
Any Update??

**Comment by rifftrader** [comment]
@BrainAxe  - Not sure mate. There's something strange going on. I spent a couple of hours messing around updating npm etc. and I'm not too sure what has fixed what.

The symptoms I have experienced are as follow:

- Missing folders as with OP.
- No missing folders but, when trying to run the project, there were module errors.

I think that there might be a problem with the eslint package. If I create a nuxt app with the eslint option selected, I seem to have problems. If I create without this option selected, everything seems to be ok from what I can see so far. After the creation of the nuxt app, I have been able to install eslint module with no dramas. Give this a shot.

**Comment by BrainAxe** [comment]
@rifftrader, I am not getting any errors. But still, folders r missing. As I am quite new to Nuxt.js, I don't have much knowledge.  Is there any update in the structure?

**Comment by congminh090800** [comment]
Are you guys still getting this error, im having this right now. The project is runnable but lacks of folders

**Comment by danielroe** [comment]
You can still create those folders and use them (see the README). They just aren't being created by default now.
