### ISSUE TITLE
Missing Folders?

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/create-nuxt-app#821]
It looks like in a latest update, some folder files were removed so folders that would normally exist for people were removed.  Example: assets, layouts.  Was this on purpose?  Some people are getting confused since docs, examples, etc.. all have these core folders in their examples.

https://github.com/nuxt/create-nuxt-app/pull/792/files

**Comment by rifftrader** [comment]
@hecktarzuli  - yes, there was previously an issued raised on here about this very topic that was marked "closed". It is as per design:

[](https://github.com/nuxt/create-nuxt-app/issues/808#issuecomment-873537891)

If you have a look at the ReadMe file in the root of a newly created app, it will give you guidance on creating those folders that you require.

**Comment by rifftrader** [comment]
[](https://github.com/nuxt/create-nuxt-app/issues/808#issuecomment-873537891)

It is as per design. If you have a look at the ReadMe in the root of a new project, it does give a bit of an explanation (curiously, it does not mention the middleware folder but this also follows the same pattern).

**Comment by Atinux** [comment]
We decided to remove them for simplicity since most of the directories are not required by default. Everything is documented in the README :)

**Comment by AllanOricil** [comment]
@danielroe 

could you guys add a flag on create-nuxt-app to let us create all these folders automatically as it was before? Like, `npx create-nuxt-app APP_NAME -c|f|a`. Add some flag name that would resamble/relate to "create a project with all folders" 

Or

at least define a list of folders we want? Like, you can add a new prompt for `npx create-nuxt-app APP_NAME`

Define your folders:
( ) components
( ) assets
( ) store
( ) plugins
( ) layouts 

It seems unnecessary but I was really used to see a project with all folders, and now I few something is missing. I have to waste time to do it by hand every time I start a new project.

**Comment by Isidorev215** [comment]
Mine does not work. I added `layouts/default.vue`. Nothing happens

**Comment by danielroe** [comment]
@Isidorev215 I'll happily look into that if you open an issue on https://github.com/nuxt/nuxt.js/issues with a reproduction.

**Comment by michael-scheurer** [comment]
> Mine does not work. I added `layouts/default.vue`. Nothing happens.
> I checked `.nuxt/app.js` and I found this: `import _6f6c098b from '.\\layouts\\default.vue'` instead of `import _6f6c098b from '..\\layouts\\default.vue'` ...
> 
> I am using `"nuxt": "^2.15.7"`

I've got the exact same error.

**Comment by Isidorev215** [comment]
After creating a nuxt project, I created the layouts folder and defined a the `default.vue` before you running `npm run dev`. 
This worked for me.
I went further to create all the next folders that I needed before running the first `npm run dev` just in case.

**Comment by Atif-Bashir-1998** [comment]
> > Mine does not work. I added `layouts/default.vue`. Nothing happens.
> > I checked `.nuxt/app.js` and I found this: `import _6f6c098b from '.\\layouts\\default.vue'` instead of `import _6f6c098b from '..\\layouts\\default.vue'` ...
> > I am using `"nuxt": "^2.15.7"`
> 
> I've got the exact same error.

Stop the server and restart it

**Comment by adnane-ka** [comment]
I'm facing this issue too, it keeps confusing me since the manual creation of layouts folder changes nothing!

**Comment by michaelmiracle018** [comment]
I'm new to nuxt. Seems the tutorials I've seen uses these layout and asset folder. How do I adjust and which folder replaces the old folders removed.

**Comment by michaelmiracle018** [comment]
or do i have to create my own?

**Comment by danielroe** [comment]
@michaelmiracle018 If you are referring to Nuxt 3, please create a discussion at https://github.com/nuxt/framework/discussions/new with some info about what you've tried. (Probably you just need to add `<NuxtLayout>` in your app.vue - see https://v3.nuxtjs.org/guide/directory-structure/layouts/#enabling-the-default-layout.)

**Comment by cryptic-dev** [comment]
Learned nuxt a month ago. I liked how scss is already included and all the folders are present, this change made things worse.

**Comment by cryptic-dev** [comment]
Learned nuxt a month ago. I liked how scss is already included and all the folders are present, this change made things worse.
I cant even get the layouts to work.
