### ISSUE TITLE
When used vant ui, ”index.vue“ file displayed "iviewui" button

### ISSUE THREAD

**Issue by liuqian1996** [nuxt/create-nuxt-app#834]
![image](https://user-images.githubusercontent.com/11707934/127176602-c88da167-1834-4f25-9031-2bc103693620.png)

**Comment by NozomuIkuta** [comment]
@liuqian1996 

This bug is already fixed by #776 and released as [v3.7.0](https://github.com/nuxt/create-nuxt-app/releases/tag/v3.7.0).
