### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Vary header contains *

### ISSUE THREAD

**Issue by mashirozx** [nuxt/create-nuxt-app#850]
When I first run the code, browser console shows this error message:

```
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Vary header contains *
    at Object.put (workbox-core.prod.js:1)
put @ workbox-core.prod.js:1
```

My config:
```
create-nuxt-app v3.7.1
✨  Generating Nuxt.js project in nuxt-job-1
? Project name: nuxt-job-1
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Nuxt.js modules:
? Linting tools: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/Jamstack hosting)
? Development tools:
? What is your GitHub username? mashirozx
? Version control system: Git

🎉  Successfully created project nuxt-demo
```

**Comment by mashirozx** [comment]
OK, here: https://github.com/mashirozx/nuxt-debug

Environment info: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2020/‎8/‎22
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

PowerShell 7.1.4
Nodejs v14.17.5
Yarn 1.22.11

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/132270269-9893b83c-f0d5-4c39-924b-50b7d82a0c31.png)

**Comment by danielroe** [comment]
@mashirozx That error is being triggered from an existing service worker you've installed on `localhost:3000` - nothing to do with this project. (Note that it doesn't replicate [in codesandbox](https://codesandbox.io/s/github/mashirozx/nuxt-debug) for that reason.) Make sure to clear your service workers in chrome://serviceworker-internals/

**Comment by mashirozx** [comment]
Oh, yeah, it's the reason, [a chrome plugin](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh?hl=zh-CN)

![image](https://user-images.githubusercontent.com/16148054/132317241-802723cc-19f8-4a09-96f9-b959b237c72a.png)

Thanks 😊
