### ISSUE TITLE
Broken Links In Documentation

### ISSUE THREAD

**Issue by robjewell-ibotta** [nuxt/create-nuxt-app#852]
I'm getting 404 responses for the links under 7 and 8 work here in the [readme](https://github.com/nuxt/create-nuxt-app/blob/master/README.md)
<img width="469" alt="Screen Shot 2021-09-16 at 10 20 13 AM" src="https://user-images.githubusercontent.com/85700100/133629106-787a7a3b-03c1-43eb-bb8c-3488d883ff7f.png">

**Comment by NozomuIkuta** [comment]
@Atinux @clarkdo 

I'm creating a PR to fix this issue, and checking links in template files as well.
I've found some links has a common domain `go.nuxtjs.dev` and they are redirected to the corresponding documentation site.

Is this domain intentionally set for the core team to manage links in template files? 
If so, I will keep them as what they are, and let you know broken redirection links if any.
If not, I will replace them all with the up-to-date links that I believe are correct.
