### ISSUE TITLE
Nuxt-Edge as selection

### ISSUE THREAD

**Issue by manniL** [nuxt/create-nuxt-app#86]
### What problem does this feature solve?

I'd love to see an option to create the Nuxt app with `nuxt-edge` instead of `nuxt` :speak_no_evil: 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c62">#c62</a>)</em></sub></div>

**Comment by Atinux** [comment]
That is a good idea yes, but I believe that should be an option given to `create-nuxt-app` directly to avoid adding one more question that most user would rarely answer "yes".

Something like `create-nuxt-app --edge <my-project>`.

If someone wants to make this PR, that would be awesome, really :100:

**Comment by NicoPennec** [comment]
I'm working on it for Hacktoberfest 🎃

@Atinux which dependency declaration is preferable in `package.json` file?

`"nuxt-edge": "latest"`
or
`"nuxt": "npm:nuxt-edge"`

**Comment by NicoPennec** [comment]
other point, we can't run `create-nuxt-app --edge <my-project>`, because it means `edge =  <my-project>` and `targetPath = .`

I recommand `create-nuxt-app <my-project> --edge`
