### ISSUE TITLE
Cannot find module './index.vue?vue&type=script&lang=ts&'

### ISSUE THREAD

**Issue by hanjonglee** [nuxt/create-nuxt-app#918]
### Version
create-nuxt-app: v4.0.0

### Steps to reproduce

1. npx create-nuxt-app@4.0.0 test
2. Select `Typescript` in Programming Language
3. npm run dev

### What is Expected?
Run without error

### What is actually happening?
Cannot find module './index.vue?vue&type=script&lang=ts&'

![image](https://user-images.githubusercontent.com/42319933/147251881-af5e835b-b9f4-4039-bbf0-49beda802fad.png)

**Comment by Sarah-Alkibsi** [comment]
try this one: 
npm install --legacy-peer-deps

**Comment by C0kkie** [comment]
@Sarah-Alkibsi  Are you sure it works? We tried and still the same error, also if we uninstall webpack
