### ISSUE TITLE
✖ Nuxt Fatal Error

### ISSUE THREAD

**Issue by artmarydotir** [nuxt/create-nuxt-app#926]
Hi, getting fatal error using  create-nuxt-app
### Version
create-nuxt-app:    4.0.0
**nuxt**:   2.15.8
**node**: v14.18.2
**vue:** 2.6.14

### Steps to reproduce
create-nuxt-app v4.0.0

Running **npm init nuxt-app <project-name>** with below option:

✨  Generating Nuxt.js project in test
? Project name: test
? Programming language: JavaScript
? Package manager: Npm
? UI framework: Vuetify.js
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: ESLint, Prettier, StyleLint
? Testing framework: None
? Rendering mode: Single Page App
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git

### What is Expected?
After running `npm run dev` command, get started.

### What is actually happening?
![Screenshot from 2022-01-25 19-01-41](https://user-images.githubusercontent.com/11363931/151007224-866ff7b7-a1f8-4cd6-b7c6-6167b15d7cb1.png)

**Comment by pi0** [comment]
Thanks for reporting issue @artmarydotir. It should be fixed please recreate lockfile (package-lock.json)

**Comment by artmarydotir** [comment]
> 

Thank you, actually i did.
`rm -rf node_modules/`
`rm package-lock.json`

still got the same error.

**Comment by pi0** [comment]
Can you please check `jiti` version in `node_modules/jiti/package.json`? `1.12.12+` should be fine.

**Comment by artmarydotir** [comment]
> Can you please check `jiti` version in `node_modules/jiti/package.json`? `1.12.12+` should be fine.

Yes, its working. thank you.
