### ISSUE TITLE
npm run dev doesn't work on new nuxt project. Error info: Plugin not found: D:\vue-cropper-nuxt\.nuxt\components\plugin.js

### ISSUE THREAD

**Issue by MygengBin** [nuxt/create-nuxt-app#949]
### Version
System: win10
create-nuxt-app: npx version
node-js: v16.15.0
npx and npm: 8.5.5

### Steps to reproduce
First run: npx create-nuxt-app 
Then run: npm run dev

### What is actually happening?
![初始化](https://user-images.githubusercontent.com/53421034/168410733-ca651e13-b9b4-475f-b895-8ce10d0f2728.png)
![运行报错](https://user-images.githubusercontent.com/53421034/168410737-e75bd922-0c51-405a-8188-efb596ca9de8.png)

**Comment by lsbqzy** [comment]
I also encountered this problem

**Comment by MygengBin** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lsbqzy** [comment]
When I built it last week, there was no problem.

The same problem occurred during the construction today. I'm sure my construction steps are consistent

**Comment by AchahbarIlias** [comment]
Same error here

**Comment by songcheng1658** [comment]
same error, in window10

**Comment by Porkts** [comment]
Same here, win10

**Comment by MygengBin** [comment]
> same error, in window10

Windows 10, me too.

**Comment by MygengBin** [comment]
> Same here, win10

Win10, me too.

**Comment by Altigar** [comment]
same error using yarn, win10

**Comment by MygengBin** [comment]
> 

I tried it. Yarn and Npm all have this error.

**Comment by Altigar** [comment]
solution here https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126714019

**Comment by MygengBin** [comment]
> solution here [nuxt/nuxt.js#10440 (comment)](https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126714019)

This can solve current error. Thank you help very much.
